### ISSUE TITLE
Material 2 branch doesn't work when running npm start

### ISSUE THREAD

**Issue by joshterrill** [AngularClass/angular2-webpack-starter#1045]
When I do a fresh checkout, then checkout the material2 branch, then run `npm install`, then `npm start` I get this:

```
Joshs-MBP:angular2-webpack-starter joshterrill$ npm start

> angular2-webpack-starter@5.0.5 start /Users/joshterrill/Projects/angular2-webpack-starter
> npm run server:dev


> angular2-webpack-starter@5.0.5 server:dev /Users/joshterrill/Projects/angular2-webpack-starter
> webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/



/Users/joshterrill/Projects/angular2-webpack-starter/node_modules/webpack/lib/webpack.js:16
                throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
        ^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOut
putPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           tslint: ...
         }
       })
     }
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownConte
xtRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.node.global should be a boolean.
 - configuration.resolve has an unknown property 'modulesDirectories'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modul
es?, plugins?, resolver?, symlinks?, unsafeCache? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/Users/joshterrill/Projects/angular2-webpack-starter/node_modules/webpack/lib/webpack.js:16:9)
    at processOptions (/Users/joshterrill/Projects/angular2-webpack-starter/node_modules/webpack-dev-server/bin/webpack-dev-server.js:269:17)
    at Object.<anonymous> (/Users/joshterrill/Projects/angular2-webpack-starter/node_modules/webpack-dev-server/bin/webpack-dev-server.js:297:1)
    at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server:dev"
npm ERR! node v4.4.7

npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.5 server:dev: `webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.0.5 server:dev script 'webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config config/webpack.dev.js --progress --profile --watch --content-base src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/joshterrill/Projects/angular2-webpack-starter/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.5 start: `npm run server:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.0.5 start script 'npm run server:dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.

```

Here's the actual log file it produced:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v4.4.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-webpack-starter@5.0.5~prestart: angular2-webpack-starter@5.0.5
6 silly lifecycle angular2-webpack-starter@5.0.5~prestart: no script for prestart, continuing
7 info lifecycle angular2-webpack-starter@5.0.5~start: angular2-webpack-starter@5.0.5
8 verbose lifecycle angular2-webpack-starter@5.0.5~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-webpack-starter@5.0.5~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/joshterrill/Projects/angular2-webpack-starter/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
10 verbose lifecycle angular2-webpack-starter@5.0.5~start: CWD: /Users/joshterrill/Projects/angular2-webpack-starter
11 silly lifecycle angular2-webpack-starter@5.0.5~start: Args: [ '-c', 'npm run server:dev' ]
12 silly lifecycle angular2-webpack-starter@5.0.5~start: Returned: code: 1  signal: null
13 info lifecycle angular2-webpack-starter@5.0.5~start: Failed to exec start script
14 verbose stack Error: angular2-webpack-starter@5.0.5 start: `npm run server:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-webpack-starter@5.0.5
16 verbose cwd /Users/joshterrill/Projects/angular2-webpack-starter
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v4.4.7
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error angular2-webpack-starter@5.0.5 start: `npm run server:dev`
22 error Exit status 1
23 error Failed at the angular2-webpack-starter@5.0.5 start script 'npm run server:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-webpack-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-webpack-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-webpack-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Is this something on my end or is this something that needs to be fixed in the code? It seems like from the error message that the version of webpack it's using doesn't allow custom to be defined in the configuration.

**Comment by dweitz43** [comment]
There is a pr to update that branch #1041

**Comment by joshterrill** [comment]
Got it.
