### ISSUE TITLE
when async form validate cause "__webpack_require__.i(...) is not a function" 

### ISSUE THREAD

**Issue by keryhu** [AngularClass/angular2-webpack-starter#1081]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
**forBuilder:**

```
buildForm(): void {
    this.form = this.fb.group({
      'name': [this.name, [], NameExist.vc,]
    })
  }
```

**async validator:**

```
export class NamelExist{

  static vc(control: NgControl):Promise<{[key: string]: any}>{
    if(!control){
      return null;
    }
    let q = new Promise((resolve, reject) => {
      setTimeout(() => {
        if (control.value === 's') {
          resolve({"taken": true});
        } else {
          resolve(null);
        }
      }, 1000)
    });
    return q;
  }

}

```

when  inserting  the name  input ,there is en err:

```
error_handler.js:46 EXCEPTION: Uncaught (in promise): TypeError: __webpack_require__.i(...) is not a functionErrorHandler.handleError @ error_handler.js:46next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81onError @ ng_zone.js:123onHandleError @ ng_zone_impl.js:65ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113_loop_1 @ zone.js:379drainMicroTaskQueue @ zone.js:386ZoneTask.invoke @ zone.js:308
error_handler.js:51 ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:51next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81onError @ ng_zone.js:123onHandleError @ ng_zone_impl.js:65ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113_loop_1 @ zone.js:379drainMicroTaskQueue @ zone.js:386ZoneTask.invoke @ zone.js:308
error_handler.js:52 Error: Uncaught (in promise): TypeError: __webpack_require__.i(...) is not a function
    at resolvePromise (http://localhost:3000/polyfills.js:15421:31)
    at http://localhost:3000/polyfills.js:15398:13
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15195:28)
    at Object.onInvoke (http://localhost:3000/vendor.js:36760:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15194:34)
    at Zone.run (http://localhost:3000/polyfills.js:15088:43)
    at http://localhost:3000/polyfills.js:15454:57
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15228:37)
    at Object.onInvokeTask (http://localhost:3000/vendor.js:36751:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15227:42)
    at Zone.runTask (http://localhost:3000/polyfills.js:15128:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.js:15360:35)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.js:15300:25)
  -------------   Elapsed: 8 ms; At: Mon Oct 03 2016 22:54:56 GMT+0800 (CST)   -------------  
    at Object.onScheduleTask (http://localhost:3000/polyfills.js:14916:18)
    at ZoneDelegate.scheduleTask (http://localhost:3000/polyfills.js:15205:49)
    at Zone.scheduleMicroTask (http://localhost:3000/polyfills.js:15142:39)
    at scheduleResolveOrReject (http://localhost:3000/polyfills.js:15452:14)
    at resolvePromise (http://localhost:3000/polyfills.js:15416:21)
    at http://localhost:3000/polyfills.js:15398:13
    at http://localhost:3000/vendor.js:52679:25
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15195:28)
    at Object.onInvoke (http://localhost:3000/vendor.js:36760:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15194:34)
    at Zone.run (http://localhost:3000/polyfills.js:15088:43)
    at http://localhost:3000/polyfills.js:15454:57
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15228:37)
    at Object.onInvokeTask (http://localhost:3000/vendor.js:36751:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15227:42)
    at Zone.runTask (http://localhost:3000/polyfills.js:15128:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.js:15360:35)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.js:15300:25)
  -------------   Elapsed: 1 ms; At: Mon Oct 03 2016 22:54:56 GMT+0800 (CST)   -------------  
    at Object.onScheduleTask (http://localhost:3000/polyfills.js:14916:18)
    at ZoneDelegate.scheduleTask (http://localhost:3000/polyfills.js:15205:49)
    at Zone.scheduleMicroTask (http://localhost:3000/polyfills.js:15142:39)
    at scheduleResolveOrReject (http://localhost:3000/polyfills.js:15452:14)
    at ZoneAwarePromise.then (http://localhost:3000/polyfills.js:15528:17)
    at http://localhost:3000/vendor.js:52657:18
    at new ZoneAwarePromise (http://localhost:3000/polyfills.js:15470:29)
    at Router.runNavigate (http://localhost:3000/vendor.js:52603:16)
    at http://localhost:3000/vendor.js:52594:67
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15195:28)
    at Object.onInvoke (http://localhost:3000/vendor.js:36760:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15194:34)
    at Zone.run (http://localhost:3000/polyfills.js:15088:43)
    at http://localhost:3000/polyfills.js:15454:57
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15228:37)
    at Object.onInvokeTask (http://localhost:3000/vendor.js:36751:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15227:42)
    at Zone.runTask (http://localhost:3000/polyfills.js:15128:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.js:15360:35)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.js:15300:25)
  -------------   Elapsed: 93 ms; At: Mon Oct 03 2016 22:54:56 GMT+0800 (CST)   -------------  
    at Object.onScheduleTask (http://localhost:3000/polyfills.js:14916:18)
    at ZoneDelegate.scheduleTask (http://localhost:3000/polyfills.js:15205:49)
    at Zone.scheduleMicroTask (http://localhost:3000/polyfills.js:15142:39)
    at scheduleResolveOrReject (http://localhost:3000/polyfills.js:15452:14)
    at ZoneAwarePromise.then (http://localhost:3000/polyfills.js:15528:17)
    at Router.scheduleNavigation (http://localhost:3000/vendor.js:52594:34)
    at Router.navigateByUrl (http://localhost:3000/vendor.js:52542:25)
    at Router.initialNavigation (http://localhost:3000/vendor.js:52399:14)
    at http://localhost:3000/vendor.js:53350:20
    at http://localhost:3000/vendor.js:26650:56
    at Array.forEach (native)
    at ApplicationRef_._loadComponent (http://localhost:3000/vendor.js:26650:19)
    at ApplicationRef_.bootstrap (http://localhost:3000/vendor.js:26636:14)
    at http://localhost:3000/vendor.js:26538:89
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (http://localhost:3000/vendor.js:26538:42)
    at http://localhost:3000/vendor.js:26506:27
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15195:28)
    at Object.onInvoke (http://localhost:3000/vendor.js:36760:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15194:34)
    at Zone.run (http://localhost:3000/polyfills.js:15088:43)
    at http://localhost:3000/polyfills.js:15454:57
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15228:37)
    at Object.onInvokeTask (http://localhost:3000/vendor.js:36751:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15227:42)
    at Zone.runTask (http://localhost:3000/polyfills.js:15128:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.js:15360:35)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.js:15300:25)
  -------------   Elapsed: 50 ms; At: Mon Oct 03 2016 22:54:56 GMT+0800 (CST)   -------------  
    at Object.onScheduleTask (http://localhost:3000/polyfills.js:14916:18)
    at ZoneDelegate.scheduleTask (http://localhost:3000/polyfills.js:15205:49)
    at Zone.scheduleMicroTask (http://localhost:3000/polyfills.js:15142:39)
    at scheduleResolveOrReject (http://localhost:3000/polyfills.js:15452:14)
    at resolvePromise (http://localhost:3000/polyfills.js:15416:21)
    at http://localhost:3000/polyfills.js:15454:17
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15228:37)
    at Object.onInvokeTask (http://localhost:3000/vendor.js:36751:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15227:42)
    at Zone.runTask (http://localhost:3000/polyfills.js:15128:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.js:15360:35)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.js:15300:25)
  -------------   Elapsed: 4 ms; At: Mon Oct 03 2016 22:54:56 GMT+0800 (CST)   -------------  
    at Object.onScheduleTask (http://localhost:3000/polyfills.js:14916:18)
    at ZoneDelegate.scheduleTask (http://localhost:3000/polyfills.js:15205:49)
    at Zone.scheduleMicroTask (http://localhost:3000/polyfills.js:15142:39)
    at scheduleResolveOrReject (http://localhost:3000/polyfills.js:15452:14)
    at ZoneAwarePromise.then (http://localhost:3000/polyfills.js:15528:17)
    at new ApplicationInitStatus (http://localhost:3000/vendor.js:26105:60)
    at NgModuleInjector.AppModuleInjector.createInternal (AppModule.ngfactory.js:488:36)
    at NgModuleInjector.create (http://localhost:3000/vendor.js:32922:76)
    at NgModuleFactory.create (http://localhost:3000/vendor.js:32907:18)
    at http://localhost:3000/vendor.js:26496:43
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15195:28)
    at Object.onInvoke (http://localhost:3000/vendor.js:36760:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15194:34)
    at Zone.run (http://localhost:3000/polyfills.js:15088:43)
    at NgZoneImpl.runInner (http://localhost:3000/vendor.js:36787:71)
    at NgZone.run (http://localhost:3000/vendor.js:36688:66)
    at PlatformRef_._bootstrapModuleFactoryWithZone (http://localhost:3000/vendor.js:26494:23)
    at http://localhost:3000/vendor.js:26533:59
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15195:28)
    at Zone.run (http://localhost:3000/polyfills.js:15088:43)
    at http://localhost:3000/polyfills.js:15454:57
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15228:37)
    at Zone.runTask (http://localhost:3000/polyfills.js:15128:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.js:15360:35)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.js:15300:25)ErrorHandler.handleError @ error_handler.js:52next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81onError @ ng_zone.js:123onHandleError @ ng_zone_impl.js:65ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113_loop_1 @ zone.js:379drainMicroTaskQueue @ zone.js:386ZoneTask.invoke @ zone.js:308
zone.js:355 Unhandled Promise rejection: __webpack_require__.i(...) is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: __webpack_require__.i(...) is not a function(…) TypeError: __webpack_require__.i(...) is not a function
    at toObservable (http://localhost:3000/vendor.js:41313:106)
    at FormControl.AbstractControl._runAsyncValidator (http://localhost:3000/vendor.js:41668:23)
    at FormControl.AbstractControl.updateValueAndValidity (http://localhost:3000/vendor.js:41642:22)
    at new FormControl (http://localhost:3000/vendor.js:41874:14)
    at FormBuilder.control (http://localhost:3000/vendor.js:41015:16)
    at FormBuilder._createControl (http://localhost:3000/vendor.js:41047:25)
    at http://localhost:3000/vendor.js:41033:43
    at Function.StringMapWrapper.forEach (http://localhost:3000/vendor.js:40327:13)
    at FormBuilder._reduceControls (http://localhost:3000/vendor.js:41032:86)
    at FormBuilder.group (http://localhost:3000/vendor.js:40999:29)
    at HomeComponent.buildForm (http://localhost:3000/main.js:20855:29)
    at HomeComponent.ngOnInit (http://localhost:3000/main.js:20850:14)
    at DebugAppView._View_HomeComponent_Host0.detectChangesInternal (HomeComponent_Host.ngfactory.js:29:82)
    at DebugAppView.AppView.detectChanges (http://localhost:3000/vendor.js:33587:14)
    at DebugAppView.detectChanges (http://localhost:3000/vendor.js:33692:44)
    at ViewRef_.detectChanges (http://localhost:3000/vendor.js:34078:20)
    at RouterOutlet.activate (http://localhost:3000/vendor.js:51760:42)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:3000/vendor.js:52979:16)
    at ActivateRoutes.activateRoutes (http://localhost:3000/vendor.js:52957:22)
    at http://localhost:3000/vendor.js:52919:19
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:3000/vendor.js:52918:29)
    at ActivateRoutes.activate (http://localhost:3000/vendor.js:52913:14)
    at http://localhost:3000/vendor.js:52654:56
    at SafeSubscriber._next (http://localhost:3000/vendor.js:65379:21)
    at SafeSubscriber.__tryOrSetError (http://localhost:3000/vendor.js:65916:16)
    at SafeSubscriber.next (http://localhost:3000/vendor.js:65858:27)
    at Subscriber._next (http://localhost:3000/vendor.js:65809:26)
    at Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.js:67754:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.js:65117:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MapSubscriber._next (http://localhost:3000/vendor.js:67492:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at ReduceSubscriber._complete (http://localhost:3000/vendor.js:67976:30)
    at ReduceSubscriber.Subscriber.complete (http://localhost:3000/vendor.js:65798:18)
    at MergeMapSubscriber._complete (http://localhost:3000/vendor.js:67746:30)
    at MergeMapSubscriber.Subscriber.complete (http://localhost:3000/vendor.js:65798:18)
    at ArrayObservable._subscribe (http://localhost:3000/vendor.js:66318:24)
    at ArrayObservable.Observable.subscribe (http://localhost:3000/vendor.js:65327:27)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MergeMapOperator.call (http://localhost:3000/vendor.js:67696:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at ReduceOperator.call (http://localhost:3000/vendor.js:67934:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MapOperator.call (http://localhost:3000/vendor.js:67463:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Object.subscribeToResult (http://localhost:3000/vendor.js:68324:27)
    at MergeMapSubscriber._innerSub (http://localhost:3000/vendor.js:67741:38)
    at MergeMapSubscriber._tryNext (http://localhost:3000/vendor.js:67738:14)
    at MergeMapSubscriber._next (http://localhost:3000/vendor.js:67721:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.js:67754:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.js:65117:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at EverySubscriber.notifyComplete (http://localhost:3000/vendor.js:67101:26)
    at EverySubscriber._complete (http://localhost:3000/vendor.js:67118:14)
    at EverySubscriber.Subscriber.complete (http://localhost:3000/vendor.js:65798:18)
    at MergeAllSubscriber._complete (http://localhost:3000/vendor.js:67597:30)
    at MergeAllSubscriber.Subscriber.complete (http://localhost:3000/vendor.js:65798:18)
    at MapSubscriber.Subscriber._complete (http://localhost:3000/vendor.js:65816:26)
    at MapSubscriber.Subscriber.complete (http://localhost:3000/vendor.js:65798:18)
    at ArrayObservable._subscribe (http://localhost:3000/vendor.js:66318:24)
    at ArrayObservable.Observable.subscribe (http://localhost:3000/vendor.js:65327:27)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MapOperator.call (http://localhost:3000/vendor.js:67463:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MergeAllOperator.call (http://localhost:3000/vendor.js:67566:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at EveryOperator.call (http://localhost:3000/vendor.js:67081:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Object.subscribeToResult (http://localhost:3000/vendor.js:68324:27)
    at MergeMapSubscriber._innerSub (http://localhost:3000/vendor.js:67741:38)
    at MergeMapSubscriber._tryNext (http://localhost:3000/vendor.js:67738:14)
    at MergeMapSubscriber._next (http://localhost:3000/vendor.js:67721:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MapSubscriber._next (http://localhost:3000/vendor.js:67492:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MapSubscriber._next (http://localhost:3000/vendor.js:67492:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MapSubscriber._next (http://localhost:3000/vendor.js:67492:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.js:67754:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.js:65117:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at Object.subscribeToResult (http://localhost:3000/vendor.js:68319:25)
    at MergeMapSubscriber._innerSub (http://localhost:3000/vendor.js:67741:38)
    at MergeMapSubscriber._tryNext (http://localhost:3000/vendor.js:67738:14)
    at MergeMapSubscriber._next (http://localhost:3000/vendor.js:67721:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.js:65809:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MapSubscriber._next (http://localhost:3000/vendor.js:67492:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.js:65809:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at FirstSubscriber._emitFinal (http://localhost:3000/vendor.js:67261:21)
    at FirstSubscriber._emit (http://localhost:3000/vendor.js:67246:14)
    at FirstSubscriber._tryPredicate (http://localhost:3000/vendor.js:67238:18)
    at FirstSubscriber._next (http://localhost:3000/vendor.js:67222:18)
    at FirstSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (http://localhost:3000/vendor.js:65452:26)
    at InnerSubscriber._next (http://localhost:3000/vendor.js:65117:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at CatchSubscriber.Subscriber._next (http://localhost:3000/vendor.js:65809:26)
    at CatchSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MergeMapSubscriber.notifyNext (http://localhost:3000/vendor.js:67754:30)
    at InnerSubscriber._next (http://localhost:3000/vendor.js:65117:21)
    at InnerSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at Object.subscribeToResult (http://localhost:3000/vendor.js:68319:25)
    at MergeMapSubscriber._innerSub (http://localhost:3000/vendor.js:67741:38)
    at MergeMapSubscriber._tryNext (http://localhost:3000/vendor.js:67738:14)
    at MergeMapSubscriber._next (http://localhost:3000/vendor.js:67721:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at ScalarObservable._subscribe (http://localhost:3000/vendor.js:66877:24)
    at ScalarObservable.Observable.subscribe (http://localhost:3000/vendor.js:65327:27)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MergeMapOperator.call (http://localhost:3000/vendor.js:67696:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at CatchOperator.call (http://localhost:3000/vendor.js:66956:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Object.subscribeToResult (http://localhost:3000/vendor.js:68324:27)
    at MergeAllSubscriber._next (http://localhost:3000/vendor.js:67588:42)
    at MergeAllSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at MapSubscriber._next (http://localhost:3000/vendor.js:67492:26)
    at MapSubscriber.Subscriber.next (http://localhost:3000/vendor.js:65773:18)
    at ArrayObservable._subscribe (http://localhost:3000/vendor.js:66316:28)
    at ArrayObservable.Observable.subscribe (http://localhost:3000/vendor.js:65327:27)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MapOperator.call (http://localhost:3000/vendor.js:67463:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MergeAllOperator.call (http://localhost:3000/vendor.js:67566:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at FirstOperator.call (http://localhost:3000/vendor.js:67199:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at CatchOperator.call (http://localhost:3000/vendor.js:66956:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MapOperator.call (http://localhost:3000/vendor.js:67463:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at CatchOperator.call (http://localhost:3000/vendor.js:66956:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MergeMapOperator.call (http://localhost:3000/vendor.js:67696:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MapOperator.call (http://localhost:3000/vendor.js:67463:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MapOperator.call (http://localhost:3000/vendor.js:67463:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MapOperator.call (http://localhost:3000/vendor.js:67463:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MergeMapOperator.call (http://localhost:3000/vendor.js:67696:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at Observable._subscribe (http://localhost:3000/vendor.js:65385:28)
    at MergeMapOperator.call (http://localhost:3000/vendor.js:67696:23)
    at Observable.subscribe (http://localhost:3000/vendor.js:65324:22)
    at http://localhost:3000/vendor.js:65358:38
    at new ZoneAwarePromise (http://localhost:3000/polyfills.js:15470:29)
    at Observable.forEach (http://localhost:3000/vendor.js:65357:16)
    at http://localhost:3000/vendor.js:52638:18
    at new ZoneAwarePromise (http://localhost:3000/polyfills.js:15470:29)
    at Router.runNavigate (http://localhost:3000/vendor.js:52603:16)
    at http://localhost:3000/vendor.js:52594:67
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15195:28)
    at Object.onInvoke (http://localhost:3000/vendor.js:36760:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.js:15194:34)
    at Zone.run (http://localhost:3000/polyfills.js:15088:43)
    at http://localhost:3000/polyfills.js:15454:57
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15228:37)
    at Object.onInvokeTask (http://localhost:3000/vendor.js:36751:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.js:15227:42)
    at Zone.runTask (http://localhost:3000/polyfills.js:15128:47)
    at drainMicroTaskQueue (http://localhost:3000/polyfills.js:15360:35)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.js:15300:25)consoleError @ zone.js:355_loop_1 @ zone.js:382drainMicroTaskQueue @ zone.js:386ZoneTask.invoke @ zone.js:308
zone.js:357 Error: Uncaught (in promise): TypeError: __webpack_require__.i(...) is not a function(…)consoleError @ zone.js:357_loop_1 @ zone.js:382drainMicroTaskQueue @ zone.js:386ZoneTask.invoke @ zone.js:308
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

insert the name input.

* **Please tell us about your environment:**

- Angular version: 2.1.0-beta.22
- Browser: [all | Chrome | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by lhammond** [comment]
hi @keryhu 
I'm getting the same issue.  how did you resolve this?
