### ISSUE TITLE
npm start error 

### ISSUE THREAD

**Issue by bigggge** [AngularClass/angular2-webpack-starter#1135]
npm start gives me errors,how can i solve it?
thanks!
**log:**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-webpack-starter@5.1.1~prestart: angular2-webpack-starter@5.1.1
6 silly lifecycle angular2-webpack-starter@5.1.1~prestart: no script for prestart, continuing
7 info lifecycle angular2-webpack-starter@5.1.1~start: angular2-webpack-starter@5.1.1
8 verbose lifecycle angular2-webpack-starter@5.1.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-webpack-starter@5.1.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/xiepan/WebProjects/angular2-webpack-starter-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle angular2-webpack-starter@5.1.1~start: CWD: /Users/xiepan/WebProjects/angular2-webpack-starter-master
11 silly lifecycle angular2-webpack-starter@5.1.1~start: Args: [ '-c', 'npm run server:dev' ]
12 silly lifecycle angular2-webpack-starter@5.1.1~start: Returned: code: 1  signal: null
13 info lifecycle angular2-webpack-starter@5.1.1~start: Failed to exec start script
14 verbose stack Error: angular2-webpack-starter@5.1.1 start: `npm run server:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-webpack-starter@5.1.1
16 verbose cwd /Users/xiepan/WebProjects/angular2-webpack-starter-master
17 error Darwin 16.1.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.0.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error angular2-webpack-starter@5.1.1 start: `npm run server:dev`
22 error Exit status 1
23 error Failed at the angular2-webpack-starter@5.1.1 start script 'npm run server:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-webpack-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-webpack-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-webpack-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by d3viant0ne** [comment]
@bigggge - There may very well be an issue with Node.js 7.x. I'll have to pull it down and try it.

A few questions to make this a bit easier.

You on macOS or some flavor of *nix?
You using an up to date, unmodified version of the seed or is this a project based on the seed?

**Comment by bigggge** [comment]
yes，i use macOS Sierra , i clone the project and not change the code

**Comment by bigggge** [comment]
@d3viant0ne i swiched to node@v6.4.0 but still not work

**Comment by bigggge** [comment]
@ i found the problem because the port 3000 is in used.thank for your reply

**Comment by d3viant0ne** [comment]
No problem. If I had $1 for every time I have done that in the past :)
