### ISSUE TITLE
branch-aot npm run build:aot fail

### ISSUE THREAD

**Issue by heqiang421** [AngularClass/angular2-webpack-starter#1143]
`> webpack --config config/webpack.aot.js  --progress --profile --bail
                                                                                           10% building modules 0/3 modules 3 active ...module-aot/client/main.browser.aot.tsError: AppModule is not an NgModule
    at AotPlugin.getNgModuleMetadata (/Users/heqiang/WebstormProjects/module-aot/node_modules/@ngtools/webpack/src/plugin.js:247:19)
    at AotPlugin._processNgModule (/Users/heqiang/WebstormProjects/module-aot/node_modules/@ngtools/webpack/src/plugin.js:230:42)
    at /Users/heqiang/WebstormProjects/module-aot/node_modules/@ngtools/webpack/src 10% building modules 3/3 modules 0 active                                         
/Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/lib/Compilation.js:197
                        _this.errors.push(err);
        ^
TypeError: Cannot read property 'errors' of null
    at errorAndCallback (/Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/lib/Compilation.js:197:9)
    at errorOrWarningAndCallback (/Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/lib/Compilation.js:228:13)
    at /Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/lib/Compilation.js:232:12
    at onDoneResolving (/Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/lib/NormalModuleFactory.js:40:20)
    at /Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/lib/NormalModuleFactory.js:117:20
    at /Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/heqiang/WebstormProjects/module-aot/node_modules/webpack/node_modules/async/lib/async.js:167:37
`
my environment:
- Angular version: 2.0.1
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

I am webpack-building-aot-app。
and
I am refering AngularClass/angular2-webpack-starter/aot
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by katallaxie** [comment]
@heqiang421 could you try again with [v6](https://github.com/AngularClass/angular2-webpack-starter/tree/v6)?! The `aot`branch was just for demoing.

**Comment by heqiang421** [comment]
v6 branch is 500.
Looks like something went wrong!

**Comment by heqiang421** [comment]
v6 branch is 500.
Looks like something went wrong!

**Comment by watiko** [comment]
I tried `npm run build:aot` on v6 branch.
Then I got:
```sh
TypeError: this.compiler.compileModules is not a function
    at CodeGenerator.codegen (/home/watiko/angular/angular2-webpack-starter/node_modules/@angular/compiler-cli/src/codegen.js:58:30)
    at codegen (/home/watiko/angular/angular2-webpack-starter/node_modules/@angular/compiler-cli/src/main.js:7:81)
    at Object.main (/home/watiko/angular/angular2-webpack-starter/node_modules/@angular/tsc-wrapped/src/main.js:30:16)
    at Object.<anonymous> (/home/watiko/angular/angular2-webpack-starter/node_modules/@angular/compiler-cli/src/main.js:16:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
Compilation failed
```

I think it comes from `@angular/compiler-cli: "^2.1.1"` in `package.json`.
Actually `2.1.1` was installed so I removed the prefixed `^` and reinstall(`yarn`) dependencies.
All things goes well.

**Comment by kjartanvalur** [comment]
What is the recommended branch to get aot? aot or v6?

**Comment by katallaxie** [comment]
@kjartanvalur I only work on [v6](https://github.com/AngularClass/angular2-webpack-starter/tree/v6). The `aot` branch was just for demo purposes.

**Comment by kjartanvalur** [comment]
ok thanks @katallaxie
