### ISSUE TITLE
validateSchema

### ISSUE THREAD

**Issue by rtaum** [AngularClass/angular2-webpack-starter#1176]
after clone repository and run "npm start" I got error 

TypeError: webpack.validateSchema is not a function
    at new Server (C:\Users\artyom_avetisyan\Documents\projects\angular2-webpack-starter\node_modules\webpack-dev-server\lib\Server.js:23:33)
    at startDevServer (C:\Users\artyom_avetisyan\Documents\projects\angular2-webpack-starter\node_modules\webpack-dev-server\bin\webpack-dev-server.js:369:12)
    at processOptions (C:\Users\artyom_avetisyan\Documents\projects\angular2-webpack-starter\node_modules\webpack-dev-server\bin\webpack-dev-server.js:307:3)
    at Object.<anonymous> (C:\Users\artyom_avetisyan\Documents\projects\angular2-webpack-starter\node_modules\webpack-dev-server\bin\webpack-dev-server.js:431:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

I suppose it is result of beta version webpack-dev-server ("webpack-dev-server": "^2.1.0-beta.9"). 
After removing 
	var validationErrors = webpack.validateSchema(optionsSchema, options);
	if(validationErrors.length) {
		throw new OptionsValidationError(validationErrors);
	}
in Server.js everything starts working.

**Comment by sdemurjian** [comment]
```
npm uninstall webpack --save-dev
npm install webpack@2.1.0-beta.25 --save-dev
npm uninstall webpack-dev-server --save-dev
npm install webpack-dev-server@2.1.0-beta.9 --save-dev
```

**Comment by Renaud009** [comment]
If I do such an update, I now get this issue: https://github.com/AngularClass/angular2-webpack-starter/issues/1036

**Comment by codeepic** [comment]
It's not working for me. Run all the commands above, still getting  `validationErrors.validateSchema is not a function` error.

**Comment by betofigueiredo** [comment]
@codeepic I found a solution here: http://stackoverflow.com/a/40613991/3520581

**Comment by coolman565** [comment]
In package.json replace 'webpack-dev-server' with 'node ./node_modules/webpack/bin/webpack.js'
This will call the local module version of webpack-dev-server and not the global one.

`"scripts": {
...
    "build:dev": "node ./node_modules/webpack/bin/webpack.js --config config/webpack.dev.js --progress --profile",
    "build:docker": "npm run build:prod && docker build -t angular2-webpack-start:latest .",
    "build:prod": "node ./node_modules/webpack/bin/webpack.js --config config/webpack.prod.js  --progress --profile --bail",
   ...
    "github-deploy:dev": "node ./node_modules/webpack/bin/webpack.js --config config/webpack.github-deploy.js --progress --profile --github-dev",
    "github-deploy:prod": "node ./node_modules/webpack/bin/webpack.js --config config/webpack.github-deploy.js --progress --profile --github-prod",
  ...
    "server:dev": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config config/webpack.dev.js --progress --profile --watch --content-base src/",
  ...
  `
