### ISSUE TITLE
Create npm scripts to run the bundled code in "production" mode

### ISSUE THREAD

**Issue by jimthedev** [AngularClass/angular2-webpack-starter#119]
Currently we use webpack-dev-server to run the project in dev. This is great but, we have the port hard coded in the package.json which isn't ideal if you want to, say, throw this up onto AWS or some other hosting where we'd expect to use `process.env.port` format. 

A user should be able to:

- [x] Run a new npm script: `npm run prod` which would run npm run build and `npm run server-prod`. 
- [x] `server-prod` should just use: 
- [x] the scripts from the `__build__` directory
- [x] a simple index.html
- [x] and `http-server`

I have a working version of this and should be able to put in a PR if this sounds like something we'd like.

**Comment by jimthedev** [comment]
Please note that after this PR our dependencies in package.json would look like this:

```
  "dependencies": {
    "@reactivex/rxjs": "5.0.0-alpha.4",
    "angular2": "2.0.0-alpha.44",
    "http-server": "0.8.5",
    "object-assign": "4.0.1",
    "reflect-metadata": "0.1.2",
    "rimraf": "2.4.3",
    "semantic-release": "^4.3.5",
    "ts-loader": "0.5.6",
    "tsd": "^0.6.5",
    "typescript": "1.6.2",
    "webpack": "1.12.2",
    "zone.js": "0.5.8"
  },

```

**Comment by jimthedev** [comment]
I'd appreciate if someone else would review this before I merge to make sure I'm not doing anything crazy. Thanks.

**Comment by SekibOmazic** [comment]
@jimthedev LGTM

**Comment by gdi2290** [comment]
I don't like having two `index.html`. Ideally there would be a `dist/` folder that has everything ready for distribution

**Comment by jimthedev** [comment]
Sounds good @gdi2290. I think all we need to do to accomplish this is to:

- [ ] create a dist folder if it doesn't exist
- [ ] copy the contents of public into dist
- [ ] copy `__build__` into dist
- [ ] add dist to .gitignore
- [ ] http server should serve from dist

Does that sound right?

**Comment by jimthedev** [comment]
@gdi2290 This is complete and I've rebased. It favors the existing index.html and uses a node script to get everything to the right locations so that dist/ is generated. Can you review again?

**Comment by juristr** [comment]
@jimthedev Mostly seems to work. Got this error though

```
> angular2-webpack-starter@0.0.0 server-prod /Users/juri/coding/angular2/tests/angular2-webpack-starter
> http-server ./dist -p $PORT

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EACCES
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "server-prod"
npm ERR! node v0.12.4
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@0.0.0 server-prod: `http-server ./dist -p $PORT`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@0.0.0 server-prod script 'http-server ./dist -p $PORT'.
npm ERR! This is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server ./dist -p $PORT
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/juri/coding/angular2/tests/angular2-webpack-starter/npm-debug.log

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "prod"
npm ERR! node v0.12.4
npm ERR! npm  v2.14.8
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@0.0.0 prod: `npm run build && node ./build.dist.js && npm run server-prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@0.0.0 prod script 'npm run build && node ./build.dist.js && npm run server-prod'.
npm ERR! This is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && node ./build.dist.js && npm run server-prod
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/juri/coding/angular2/tests/angular2-webpack-starter/npm-debug.log
```

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-webpack-starter/compare/cf4b3f2bf4fc74de37aa6af05a891d29c7c2d0a8...master
