### ISSUE TITLE
import components in unit tests

### ISSUE THREAD

**Issue by arozwalak** [AngularClass/angular2-webpack-starter#124]
I'm trying to import app.ts into unit tests, but I don't know how it should work. I used https://github.com/juliemr/ng2-test-seed to get tests working so my test file looks like this:

```
/// <reference path="../../src/typings/_custom.d.ts" />
import { it, iit, describe, expect, inject, injectAsync, beforeEachProviders, fakeAsync, tick } from 'angular2/testing';

import { App } from '../../src/app/app';

describe('App', () => {
  beforeEachProviders(() => [App])

  it('should provide test', inject([App], (app) => {
    expect(app.test).toEqual('test');
  }));
})
```

and my app.ts files:

```
import { Component, Injectable } from 'angular2/angular2';

@Component({
    selector: 'app',
    template: '<div></div>'
})

@Injectable()
export class App {
    test: String = 'test';
    constructor() {
    }
}
```

In result I'm getting:

```
Chrome 46.0.2490 (Mac OS X 10.10.5) App should provide test FAILED
        TypeError: Cannot read property 'getXHR' of undefined
            at _getAppBindings (/Users/arozwalak/Sites/gherkin/admin-portal/admin-portal-web/spec.bundle.js:34118:63 <- webpack:///~/angular2/src/testing/test_injector.js:91:33)
            at Object.createTestInjector (/Users/arozwalak/Sites/gherkin/admin-portal/admin-portal-web/spec.bundle.js:34128:80 <- webpack:///~/angular2/src/testing/test_injector.js:101:0)
            at Object.<anonymous> (/Users/arozwalak/Sites/gherkin/admin-portal/admin-portal-web/spec.bundle.js:33929:49 <- webpack:///~/angular2/src/testing/testing.js:67:0)
Chrome 46.0.2490 (Mac OS X 10.10.5): Executed 2 of 3 (1 FAILED) (skipped 1) (0.115 secs / 0.019 secs)
```

I also tried with `injectAsync` but have the same result.

**Comment by Ao21** [comment]
I had the same problem, if you add

```javascript
var domAdapter = require('angular2/src/core/dom/browser_adapter').BrowserDomAdapter;
domAdapter.makeCurrent();
```

to the spec.bundle.js after the requires, seems to solve it for me.

**Comment by matthewdenobrega** [comment]
FYI in the test seed this is done in the karma-test-shim.js file - https://github.com/juliemr/ng2-test-seed/blob/master/karma-test-shim.js (line 32) https://github.com/juliemr/ng2-test-seed/blob/master/karma-test-shim.js

**Comment by gdi2290** [comment]
@Ao21 can you make a pull-request

**Comment by gdi2290** [comment]
done via https://github.com/AngularClass/angular2-webpack-starter/pull/128
