### ISSUE TITLE
webpack-dev-server has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by smirciat** [AngularClass/angular2-webpack-starter#1279]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

report a *bug*?**

```
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration.port should be a number.
```

* **What is the current behavior?**
Fresh git clone fails on npm run server:dev

* **What is the expected behavior?**
Trying to get initial setup to run server:dev

* **Please tell us about your environment:**

- Angular version: 2.2.1
- Browser: N/A didn't get that far

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ubuntu/.nvm/versions/node/v7.2.1/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v7.2.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.0.5
3 info using node@v7.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-webpack-starter@5.1.1~prestart: angular2-webpack-starter@5.1.1
6 silly lifecycle angular2-webpack-starter@5.1.1~prestart: no script for prestart, continuing
7 info lifecycle angular2-webpack-starter@5.1.1~start: angular2-webpack-starter@5.1.1
8 verbose lifecycle angular2-webpack-starter@5.1.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-webpack-starter@5.1.1~start: PATH: /home/ubuntu/.nvm/versions/node/v7.2.1/lib/node_modules/npm/bin/node-gyp-bin:/home/ubuntu/workspace/angular2-webpack-starter/node_modules/.bin:/home/ubuntu/.nvm/versions/node/v7.2.1/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/mnt/shared/bin:/home/ubuntu/workspace/node_modules/.bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/shared/sbin:/opt/gitl:/opt/go/bin:/mnt/shared/c9/app.nw/bin:/usr/local/rvm/bin
10 verbose lifecycle angular2-webpack-starter@5.1.1~start: CWD: /home/ubuntu/workspace/angular2-webpack-starter
11 silly lifecycle angular2-webpack-starter@5.1.1~start: Args: [ '-c', 'npm run server:dev' ]
12 silly lifecycle angular2-webpack-starter@5.1.1~start: Returned: code: 1  signal: null
13 info lifecycle angular2-webpack-starter@5.1.1~start: Failed to exec start script
14 verbose stack Error: angular2-webpack-starter@5.1.1 start: `npm run server:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v7.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-webpack-starter@5.1.1
16 verbose cwd /home/ubuntu/workspace/angular2-webpack-starter
17 error Linux 4.2.0-c9
18 error argv "/home/ubuntu/.nvm/versions/node/v7.2.1/bin/node" "/home/ubuntu/.nvm/versions/node/v7.2.1/bin/npm" "start"
19 error node v7.2.1
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error angular2-webpack-starter@5.1.1 start: `npm run server:dev`
22 error Exit status 1
23 error Failed at the angular2-webpack-starter@5.1.1 start script 'npm run server:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-webpack-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-webpack-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-webpack-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by smirciat** [comment]
process.env.PORT was resolving to a string '8080' instead of a number.

**Comment by Disput** [comment]
You wrote the issue but I don't find a solution
