### ISSUE TITLE
TypeError: remap is not a function

### ISSUE THREAD

**Issue by battmanz** [AngularClass/angular2-webpack-starter#1283]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

The following error shows up in the terminal after running the unit tests:

```
ERROR [coverage]: TypeError: remap is not a function
    at onCoverageComplete (/Users/mattbanz/Desktop/angular2-webpack-starter/node_modules/karma-remap-coverage/remap-coverage.js:23:23)
    at .<anonymous> (/Users/mattbanz/Desktop/angular2-webpack-starter/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at InMemoryReport.writeReport (/Users/mattbanz/Desktop/angular2-webpack-starter/node_modules/karma-coverage/lib/in-memory-report.js:14:22)
    at writeReport (/Users/mattbanz/Desktop/angular2-webpack-starter/node_modules/karma-coverage/lib/reporter.js:68:16)
    at /Users/mattbanz/Desktop/angular2-webpack-starter/node_modules/karma-coverage/lib/reporter.js:290:11
    at Array.forEach (native)
    at forEach (/Users/mattbanz/Desktop/angular2-webpack-starter/node_modules/karma/lib/browser_collection.js:93:21)
    at /Users/mattbanz/Desktop/angular2-webpack-starter/node_modules/karma-coverage/lib/reporter.js:247:16
    at Array.forEach (native)
    at onRunComplete (/Users/mattbanz/Desktop/angular2-webpack-starter/node_modules/karma-coverage/lib/reporter.js:246:15)
    at .<anonymous> (/Users/mattbanz/Desktop/angular2-webpack-starter/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:111:20)
    at emit (events.js:191:7)
    at emitRunCompleteIfAllBrowsersDone (/Users/mattbanz/Desktop/angular2-webpack-starter/node_modules/karma/lib/server.js:294:12)
```

* **If the current behavior is a bug, please provide the steps to reproduce**

1. clone the repo
2. npm install
3. npm test

* **What is the expected behavior?**

No error in the terminal

* **What is the motivation / use case for changing the behavior?**

Errors are bad and ugly

* **Please tell us about your environment:**

Angular 2.2.1
no browser, just run the tests in the terminal

**Comment by vtabary** [comment]
It seems that it's a problem with the library karma-remap-coverage : https://github.com/sshev/karma-remap-coverage/issues/12

You have to force the remap-istanbul library version to 0.8.1 (maybe 0.8.0) in your package.json as a workaround : 
```
$ npm run install --save-dev remap-istanbul@0.8.1
```

**Comment by battmanz** [comment]
@vtabary Thanks for your reply! I got it working with 0.8.0. I got a different error with 0.8.1.

**Comment by kaisinter** [comment]
@vtabary Just worked for me too with 0.81. Thank you so much!

**Comment by JoelParke** [comment]
I did a npm install remap-istanbul 
which installed @0.8.4 and all worked without errors for 'npm run test'

**Comment by katallaxie** [comment]
Should work with current `master` now.
