### ISSUE TITLE
creating mixed Component

### ISSUE THREAD

**Issue by yalaa90** [AngularClass/angular2-webpack-starter#1389]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ X] bug report
[ ] feature request
[X ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Hi,

i'm trying to put a component in app.component
like that 
@Component({
  selector: 'app',
  encapsulation: ViewEncapsulation.None,
  styleUrls: [
    './app.component.css'
  ],
  template: `
<hr-test></hr-test>
......

 but it throws exception 

Uncaught TypeError: Cannot set property 'stack' of undefined
    at SyntaxError.set [as stack] (http://localhost:3000/vendor.dll.js:70906:61)
    at assignAll (http://localhost:3000/polyfills.dll.js:4691:29)
    at SyntaxError.ZoneAwareError (http://localhost:3000/polyfills.dll.js:4762:16)
    at SyntaxError.BaseError [as constructor] (http://localhost:3000/vendor.dll.js:70868:16)
    at new SyntaxError (http://localhost:3000/vendor.dll.js:6256:16)
    at componentModuleUrl (http://localhost:3000/vendor.dll.js:19018:15)
    at CompileMetadataResolver._loadDirectiveMetadata (http://localhost:3000/vendor.dll.js:18135:28)
    at http://localhost:3000/vendor.dll.js:18309:54
    at Array.forEach (native)
    at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (http://localhost:3000/vendor.dll.js:18308:41)
    at http://localhost:3000/vendor.dll.js:51731:58
    at Array.forEach (native)
    at JitCompiler._loadModules (http://localhost:3000/vendor.dll.js:51730:43)
    at JitCompiler._compileModuleAndComponents (http://localhost:3000/vendor.dll.js:51685:52)
    at JitCompiler.compileModuleAsync (http://localhost:3000/vendor.dll.js:51651:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:3000/vendor.dll.js:39636:25)
    at PlatformRef_.bootstrapModule (http://localhost:3000/vendor.dll.js:39611:21)
    at HTMLDocument.main (http://localhost:3000/main.bundle.js:2366:10)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.dll.js:4262:35)
    at Zone.runTask (http://localhost:3000/polyfills.dll.js:4138:47)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.dll.js:4332:33)
set @ errors.js:68
assignAll @ zone.js:704
ZoneAwareError @ zone.js:775
BaseError @ errors.js:30
SyntaxError @ util.js:163
componentModuleUrl @ metadata_resolver.js:1113
CompileMetadataResolver._loadDirectiveMetadata @ metadata_resolver.js:230
(anonymous) @ metadata_resolver.js:404
CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata @ metadata_resolver.js:403
(anonymous) @ compiler.js:189
JitCompiler._loadModules @ compiler.js:188
JitCompiler._compileModuleAndComponents @ compiler.js:143
JitCompiler.compileModuleAsync @ compiler.js:109
PlatformRef_._bootstrapModuleWithZone @ application_ref.js:416
PlatformRef_.bootstrapModule @ application_ref.js:391
main @ main.browser.ts:27
ZoneDelegate.invokeTask @ zone.js:275
Zone.runTask @ zone.js:151
ZoneTask.invoke @ zone.js:345

----------------------------------------------------------
but when i try about.component.ts like that  <about></about>

it works fine

i have just clone the  project so all config , packjson ,etc are the same

**Comment by sasidhar** [comment]
@yalaa90 The issue is in Zone.js.

Refer : https://github.com/angular/zone.js/issues/427

Could you please update zone.js to `0.7.6` and try again?
