### ISSUE TITLE
Unit test errors: Can't find variable: injectAsync/beforeEachProviders/inject

### ISSUE THREAD

**Issue by yaroslavya** [AngularClass/angular2-webpack-starter#143]
Just cloned the latest version like that:
`git clone https://github.com/AngularClass/angular2-webpack-starter.git`
then
`npm install `
after everything was installed( ofc made sure I installed the webpack globally ) I typed `npm test` in the console and I have the following errors:
 ReferenceError: Can't find variable: **injectAsync**
            at C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:45167 <- webpack:///src/app/app.spec.ts:26:2
            at C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:45168 <- webpack:///src/app/app.spec.ts:28:0
            at __webpack_require__ (C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:20 <- webpack:/webpack/bootstrap 9cf4d04ebf779bc4a1dc:19:0)
            at webpackContext (C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:45117 <- webpack:/src \.spec\.ts:5:0)

 ReferenceError: Can't find variable: **beforeEachProviders**
            at C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:45178 <- webpack:///src/app/app.spec.ts:41:3
            at C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:45182 <- webpack:///src/app/app.spec.ts:47:0
            at __webpack_require__ (C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:20 <- webpack:/webpack/bootstrap 9cf4d04ebf779bc4a1dc:19:0)
            at webpackContext (C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:45117 <- webpack:/src \.spec\.ts:5:0)

ReferenceError: Can't find variable: **inject**
            at C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:38331 <- webpack:///test/injector.spec.ts:7:2
            at C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:38332 <- webpack:///test/injector.spec.ts:8:0
            at __webpack_require__ (C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:20 <- webpack:/webpack/bootstrap 9cf4d04ebf779bc4a1dc:19:0)
            at webpackContext (C:/programming/playground/ngt2/angular2-webpack-starter/spec-bundle.js:38310 <- webpack:/test \.spec\.ts:6:0)

**Comment by JamesHenry** [comment]
I am experiencing the same issue - fresh clone, latest typescript, npm install...

**Comment by yaroslavya** [comment]
[This commit](https://github.com/AngularClass/angular2-webpack-starter/commit/42776931adbe1c9bbc2f8bbd8df41fec6c5155cf) seem to be solved this issue.
