### ISSUE TITLE
Angular 4 compatibility?

### ISSUE THREAD

**Issue by klihelp** [AngularClass/angular2-webpack-starter#1644]
Angular 4 is out this week 
- mainly your project need to update dependencies; imports usage; ng-template..

**Comment by acostaf** [comment]
@klihelp what do you mean with "imports usage" ? I am not aware about any changes on imports

**Comment by klihelp** [comment]
Dependency update for both Angular 2 and 4 would be good.

Imports in your projects is ok, some projects imported from subdirectories..
> import { Response } from '@angular/http/src/static_response'

**Comment by itranga** [comment]
Please try 
npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@latest --save

**Comment by Aaltuj** [comment]
Updating to latest version of angular suggested by @itranga results in`> angular2-webpack-starter@5.4.1 server:dev D:\Dev\playground\angular2-webpack-
starter-master                                                                 
> webpack-dev-server --config config/webpack.dev.js --open --progress --profile
 --watch --content-base src/                                                   
                                                                               
Error: Cannot find module '@angular/tsc-wrapped'                               
    at Function.Module._resolveFilename (module.js:455:15)                     
    at Function.Module._load (module.js:403:25)                                
    at Module.require (module.js:483:17)                                       
    at require (internal/module.js:20:19)                                      
    at Object.<anonymous> (D:\Dev\playground\angular2-webpack-starter-master\pa
ckages\compiler-cli\src\compiler_host.ts:10:1)                                 
    at Module._compile (module.js:556:32)                                      
    at Object.Module._extensions..js (module.js:565:10)                        
    at Module.load (module.js:473:32)                                          
    at tryModuleLoad (module.js:432:12)                                        
    at Function.Module._load (module.js:424:3)                                 
    at Module.require (module.js:483:17)                                       
    at require (internal/module.js:20:19)                                      
    at Object.<anonymous> (D:\Dev\playground\angular2-webpack-starter-master\pa
ckages\compiler-cli\src\codegen.ts:19:1)                                       
    at Module._compile (module.js:556:32)                                      
    at Object.Module._extensions..js (module.js:565:10)                        
    at Module.load (module.js:473:32)                                          
    at tryModuleLoad (module.js:432:12)                                        
    at Function.Module._load (module.js:424:3)                                 
    at Module.require (module.js:483:17)                                       
    at require (internal/module.js:20:19)                                      
    at Object.<anonymous> (D:\Dev\playground\angular2-webpack-starter-master\pa
ckages\compiler-cli\index.ts:9:1)                                              
    at Module._compile (module.js:556:32)                                      `

**Comment by klihelp** [comment]
another, update angular-cli to @angular/cli

**Comment by moravcik** [comment]
After update suggested by @itranga the `npm start` works (with errors in console) but any of `npm build`(s) crashed on some 1000+ errors from `[at-loader]`. Did you have any luck with building using Angular 4?

**Comment by klihelp** [comment]
`[at-loader]` errors are type errors for all npm modules you use, including this project

**Comment by BallisticPain** [comment]
Another bit that will be necessary to get Angular v4 working with @AngularClass Seed is... to remove some items from `webpack.common.js` I speak of this here: https://github.com/yuyang041060120/ng2-validation/issues/68#issuecomment-292701869

**Comment by WillooWisp** [comment]
Is this "angular2-webpack-starter" being deprecated? Before there where a lot of progress, keeping the project up to date with angular and typescript etc, but in the last month or so nothing has really happened. How about a new release with official angular "4" support?

**Comment by tsukhu** [comment]
Thanks @Aaltuj , @itranga using these two steps I was able to update to ng4
1) npm install @angular/{common,compiler,compiler-cli,core,forms,http,platform-browser,platform-browser-dynamic,platform-server,router,animations}@latest typescript@latest --save
2) npm install @angular/tsc-wrapped --save
3) in x-large,directive to import { By } from '@angular/platform-browser';

**Comment by gdi2290** [comment]
Thank you for the issue. Please follow issue https://github.com/AngularClass/angular2-webpack-starter/issues/1686 for updates into Angular version 4+
