### ISSUE TITLE
Errors in IE 10/11

### ISSUE THREAD

**Issue by shawnrmoss** [AngularClass/angular2-webpack-starter#213]
I started with a fresh clone of the repo. Then ran
- npm install : works great.
-npm run start : builds the app and runs at localhost:3000://

Works fine in Chrome, Opera, and Firefox and Edge.  But I get this error running it in IE 10 and IE 11.  

Any help with this would be greatly appreciated.

Thanks in advance!

 EXCEPTION: SyntaxError: The use of a keyword for an identifier is invalid 
STACKTRACE: 
SyntaxError: The use of a keyword for an identifier is invalid
   at evalExpression (http://localhost:3000/vendor.bundle.js:1908:6)
   at _createViewFactoryRuntime (http://localhost:3000/vendor.bundle.js:24965:14)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:24926:22)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:14174:26)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8)
   at lib$es6$promise$$internal$$tryCatch (http://localhost:3000/vendor.bundle.js:39379:10)
   at lib$es6$promise$$internal$$invokeCallback (http://localhost:3000/vendor.bundle.js:39391:10)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:39939:14)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40611:6)
   at microtask (http://localhost:3000/vendor.bundle.js:14214:30)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:14174:26)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8)
   at lib$es6$promise$asap$$flush (http://localhost:3000/vendor.bundle.js:39173:10)
   at cb (http://localhost:3000/vendor.bundle.js:14232:26)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40719:12)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40141:8)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:14174:26)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8)

-----async gap-----
Error
   at _getStacktraceWithCaughtError (http://localhost:3000/vendor.bundle.js:42482:6)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:42535:8)
   at bind (http://localhost:3000/vendor.bundle.js:40132:6)
   at bindArguments (http://localhost:3000/vendor.bundle.js:40366:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40386:10)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:24923:18)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:14174:26)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8)
   at lib$es6$promise$$internal$$tryCatch (http://localhost:3000/vendor.bundle.js:39379:10)
   at lib$es6$promise$$internal$$invokeCallback (http://localhost:3000/vendor.bundle.js:39391:10)
   at lib$es6$promise$$internal$$publish (http://localhost:3000/vendor.bundle.js:39362:12)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40611:6)
   at microtask (http://localhost:3000/vendor.bundle.js:14214:30)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:14174:26)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8)
   at lib$es6$promise$asap$$flush (http://localhost:3000/vendor.bundle.js:39173:10)
   at cb (http://localhost:3000/vendor.bundle.js:14232:26)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40719:12)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40141:8)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:14174:26)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8)

-----async gap-----
Error
   at _getStacktraceWithCaughtError (http://localhost:3000/vendor.bundle.js:42482:6)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:42535:8)
   at bind (http://localhost:3000/vendor.bundle.js:40132:6)
   at bindArguments (http://localhost:3000/vendor.bundle.js:40366:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40386:10)
   at _compileComponentRuntime (http://localhost:3000/vendor.bundle.js:24914:14)
   at _compileNestedComponentRuntime (http://localhost:3000/vendor.bundle.js:24940:10)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:24922:75)
   at forEach (http://localhost:3000/vendor.bundle.js:36696:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:24922:18)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:14174:26)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8)
   at lib$es6$promise$$internal$$tryCatch (http://localhost:3000/vendor.bundle.js:39379:10)
   at lib$es6$promise$$internal$$invokeCallback (http://localhost:3000/vendor.bundle.js:39391:10)
   at lib$es6$promise$$internal$$publish (http://localhost:3000/vendor.bundle.js:39362:12)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40611:6)
   at microtask (http://localhost:3000/vendor.bundle.js:14214:30)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:14174:26)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8)
   at lib$es6$promise$asap$$flush (http://localhost:3000/vendor.bundle.js:39173:10)
   at cb (http://localhost:3000/vendor.bundle.js:14232:26)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40719:12)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40141:8)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:14174:26)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8)

-----async gap-----
Error
   at _getStacktraceWithCaughtError (http://localhost:3000/vendor.bundle.js:42482:6)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:42535:8)
   at bind (http://localhost:3000/vendor.bundle.js:40132:6)
   at bindArguments (http://localhost:3000/vendor.bundle.js:40366:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:40386:10)
   at _compileComponentRuntime (http://localhost:3000/vendor.bundle.js:24914:14)
   at compileHostComponentRuntime (http://localhost:3000/vendor.bundle.js:24866:14)
   at compileInHost (http://localhost:3000/vendor.bundle.js:24767:10)
   at loadAsRoot (http://localhost:3000/vendor.bundle.js:14584:10)
   at useFactory (http://localhost:3000/vendor.bundle.js:13466:18)
   at _instantiate (http://localhost:3000/vendor.bundle.js:3363:22)
   at _instantiateProvider (http://localhost:3000/vendor.bundle.js:3314:14)
   at _new (http://localhost:3000/vendor.bundle.js:3303:10)
   at getObjByKeyId (http://localhost:3000/vendor.bundle.js:2816:18)
   at _getByKeyDefault (http://localhost:3000/vendor.bundle.js:3499:14)
   at _getByKey (http://localhost:3000/vendor.bundle.js:3445:14)
   at get (http://localhost:3000/vendor.bundle.js:3122:10)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:13738:18)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:14174:26)
   at run (http://localhost:3000/vendor.bundle.js:14123:18)
   at bootstrap (http://localhost:3000/vendor.bundle.js:13729:10)
   at bootstrap (http://localhost:3000/vendor.bundle.js:17616:6)
   at main (http://localhost:3000/main.bundle.js:12:6)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8)

-----async gap-----
Error
   at _getStacktraceWithCaughtError (http://localhost:3000/vendor.bundle.js:42482:6)
   at Anonymous function (http://localhost:3000/vendor.bundle.js:42535:8)
   at _createInnerZone (http://localhost:3000/vendor.bundle.js:14161:10)
   at NgZone (http://localhost:3000/vendor.bundle.js:13948:14)
   at createNgZone (http://localhost:3000/vendor.bundle.js:13489:6)
   at application (http://localhost:3000/vendor.bundle.js:13590:10)
   at bootstrap (http://localhost:3000/vendor.bundle.js:17616:6)
   at main (http://localhost:3000/main.bundle.js:12:6)
   at run (http://localhost:3000/vendor.bundle.js:40161:8)
   at zoneBoundFn (http://localhost:3000/vendor.bundle.js:40134:8) 
SyntaxError: The use of a keyword for an identifier is invalid

**Comment by alvipeo** [comment]
Same here.

**Comment by gdi2290** [comment]
I took the time to download a windows VM and seen the same error :/ I'm not too sure how to fix it. I think it might even be due to the recent beta.1 release. Can you revert to beta.0 and see if you run into the same error

**Comment by shawnrmoss** [comment]
Yep that did it!  Thanks so much.

**Comment by nolazybits** [comment]
I had the same problem and reverting to beta.0 fixed it. Thanks!

**Comment by qdb** [comment]
https://github.com/angular/angular/issues/6501

**Comment by ps2goat** [comment]
+1, but we're having issues with the beta.0 lifecycle hooks not firing correctly in IE 10/11.  Works fine in Chrome.

**Comment by gdi2290** [comment]
I added an `ie-shim` and there might be problems with the angular2 repo. I'm going to close this for now

**Comment by ps2goat** [comment]
The shim works!  It would be great to get this into the polyfills.

**Comment by gdi2290** [comment]
I switched to core-js which has all of them and more

**Comment by ps2goat** [comment]
@gdi2290 do you use that instead of the angular2 polyfills?

**Comment by gdi2290** [comment]
yup, it's simpler just to use one module for all the polyfills that are updated than many outdated polyfills
