### ISSUE TITLE
Exception when running in a prod mode

### ISSUE THREAD

**Issue by yaroslavya** [AngularClass/angular2-webpack-starter#218]
I made git clone to make sure I have the newest version. Then executed the following

`npm run postinstall`
`npm run build:prod`
`npm run server:prod`

I see the following error in the console after opening the solution in chrome/firefox: "EXCEPTION: No Directive annotation found on t"

stacktrace:

vendor.21ec1defc4f632521815.bundle.js:15 Error: No Directive annotation found on t
    at new e (http://192.168.0.48:8080/vendor.21ec1defc4f632521815.bundle.js:1:21314)
    at t.resolve (http://192.168.0.48:8080/vendor.21ec1defc4f632521815.bundle.js:5:23781)
    at t.getResolvedDirectiveMetadata (http://192.168.0.48:8080/vendor.21ec1defc4f632521815.bundle.js:14:18609)
    at Function.t.create (http://192.168.0.48:8080/vendor.21ec1defc4f632521815.bundle.js:3:28336)
    at eval (viewFactory_t:143:37)
    at Object.A [as evalExpression] (http://192.168.0.48:8080/vendor.21ec1defc4f632521815.bundle.js:1:2686)
    at t._createViewFactoryRuntime (http://192.168.0.48:8080/vendor.21ec1defc4f632521815.bundle.js:8:13474)
    at http://192.168.0.48:8080/vendor.21ec1defc4f632521815.bundle.js:8:12136
    at r.run (http://192.168.0.48:8080/vendor.21ec1defc4f632521815.bundle.js:24:15590)
    at r.run (http://192.168.0.48:8080/vendor.21ec1defc4f632521815.bundle.js:6:9366)e.logError @ vendor.21ec1defc4f632521815.bundle.js:15

**Comment by BaggersIO** [comment]
I just ran into the same issue.

**Comment by mastertinner** [comment]
+1

**Comment by gdi2290** [comment]
this is a problem with beta.1 see workaround https://github.com/AngularClass/angular2-webpack-starter/commit/893d421b76bb3ded85fba3fb1cbbb8cefa57079d

**Comment by mastertinner** [comment]
thanks a lot, @gdi2290! that fixed it.

**Comment by phil-lgr** [comment]
+1 thanks @gdi2290 for the workaround

**Comment by valorkin** [comment]
thanks a lot! :)

**Comment by gdi2290** [comment]
oops, I'm going to keep this open for others to see

**Comment by gdi2290** [comment]
closing this since I have a workaround and it's a problem with angular2 at the moment
