### ISSUE TITLE
how to integrate with Wallaby.js

### ISSUE THREAD

**Issue by pashaie** [AngularClass/angular2-webpack-starter#242]
Have any one tried to use wallaby.js with this project?
my wallaby.json is
```javascript
{
  "files": [
    "node_modules/angular/angular.js",
    "node_modules/angular-route/angular-route.js",
    "node_modules/angular-mocks/angular-mocks.js",
    "src/**/*.ts"
  ],
  "tests": [
    "src/**/*.spec.ts"
  ]
}
```

but I'm getting error:
```
ReferenceError: Can't find variable: require
	at src/app/app.spec.ts:1

ReferenceError: Can't find variable: require
	at src/app/app.ts:4

ReferenceError: Can't find variable: require
	at src/app/directives/router-active.ts:2

ReferenceError: Can't find variable: require
	at src/app/home/directives/x-large.spec.ts:1

ReferenceError: Can't find variable: require
	at src/app/home/directives/x-large.ts:1

ReferenceError: Can't find variable: require
	at src/app/home/home.spec.ts:1

ReferenceError: Can't find variable: require
	at src/app/home/home.ts:1

ReferenceError: Can't find variable: require
	at src/app/home/providers/title.spec.ts:1

ReferenceError: Can't find variable: require
	at src/app/home/providers/title.ts:1

ReferenceError: Can't find variable: require
	at src/main.ts:4

ReferenceError: Can't find variable: require
	at src/vendor.ts:2

ReferenceError: Can't find variable: require
	at src/app/app.spec.ts:1

ReferenceError: Can't find variable: require
	at src/app/app.ts:4

ReferenceError: Can't find variable: require
	at src/app/directives/router-active.ts:2

ReferenceError: Can't find variable: require
	at src/app/home/directives/x-large.spec.ts:1

ReferenceError: Can't find variable: require
	at src/app/home/directives/x-large.ts:1

ReferenceError: Can't find variable: require
	at src/app/home/home.spec.ts:1

ReferenceError: Can't find variable: require
	at src/app/home/home.ts:1

ReferenceError: Can't find variable: require
	at src/app/home/providers/title.spec.ts:1

ReferenceError: Can't find variable: require
	at src/app/home/providers/title.ts:1

ReferenceError: Can't find variable: require
	at src/main.ts:4

ReferenceError: Can't find variable: require
	at src/vendor.ts:2


```

**Comment by valorkin** [comment]
@pashaie check this https://github.com/wallabyjs/public/issues/54
and http://wallabyjs.com/docs/integration/node.html
should help

**Comment by valorkin** [comment]
and one more to go

**Comment by pashaie** [comment]
@valorkin thanks for your help.
updating my wallbay.js to
```javascript
var webpackConfig = require('./webpack.config');
var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function () {
  return {
    files: [
      "node_modules/angular/angular.js",
      "node_modules/angular-route/angular-route.js",
      "node_modules/angular-mocks/angular-mocks.js",
      "src/**/*.ts",
      "!src/**/*.spec.ts"
    ],

    tests: [
      "src/**/*.spec.ts"
    ],

    env: {
      type: 'node'
      //params: {
      //  env: 'NODE_PATH=/a/b/c;HOME=/Users/a/b'
      //}
    },

	postprocessor: wallabyPostprocessor,

    bootstrap: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    }
  };
};
```
there is still errors
```
Runtime error: ReferenceError: window is not defined
    at Object.<anonymous> (.\src\app\app.spec.js.wbp.js:1:63)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Array.forEach (native)
Runtime error: ReferenceError: window is not defined
    at Object.<anonymous> (.\src\app\home\home.spec.js.wbp.js:1:63)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Array.forEach (native)
Runtime error: ReferenceError: window is not defined
    at Object.<anonymous> (.\src\app\home\directives\x-large.spec.js.wbp.js:1:63)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Array.forEach (native)
Runtime error: ReferenceError: window is not defined
    at Object.<anonymous> (.\src\app\home\providers\title.spec.js.wbp.js:1:63)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Array.forEach (native)
```

**Comment by ArtemGovorov** [comment]
@pashaie Here is the fork of the project with the working wallaby config - https://github.com/wallabyjs/angular2-webpack-starter/blob/master/wallaby.js

**Comment by pashaie** [comment]
@ArtemGovorov thanks

**Comment by gdi2290** [comment]
@ArtemGovorov thanks! I created a wiki page you can update https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-integrate-with-Wallaby.js

**Comment by ArtemGovorov** [comment]
@gdi2290 Awesome, thanks!

**Comment by kjr247** [comment]
I know this is pretty old, but just for my edification on what happened here. You added the ignore to the test files? Was that the only change? - sent on mobile

**Comment by ArtemGovorov** [comment]
@kjr247 I have added `load: false` for all files (like [described here](https://wallabyjs.com/docs/integration/webpack.html)).
