### ISSUE TITLE
Cannot find module 'process-nextick-args'

### ISSUE THREAD

**Issue by KhoaSydney** [AngularClass/angular2-webpack-starter#310]
Hi,

I followed the instruction and ran npm install but it gives me the following error:

```javascript

typings install

module.js:328
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\khoa_2\Documents\projects\justbooked.com.au\justbooked.com.au\node_modules\typings\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_modules\got\node_modules\readable-stream\lib\_stream_readable.js:6:23)
```

Anyone know why?

cheers,
Khoa

**Comment by gdi2290** [comment]
If you're on npm version 2.x.x then windows has a limit of folder depth. You can update to `npm@3` via `npm install -g npm@3` then run `npm cache clear` and delete your `node_modules/` before installing again

**Comment by KhoaSydney** [comment]
hi @gdi2290,

Installed npm 3 fix the issue. thanks
