### ISSUE TITLE
e2e tests fail to run- SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by jmiazga** [AngularClass/angular2-webpack-starter#347]
After cloning the repo and doing a npm install, I run the command ```npm run e2e``` and get the following error:

```
SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at Object.<anonymous> (C:\Development\angular2-webpack-starter\node_modules\ts-node\src\bin\ts-node.ts:121:12)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
```

**Comment by gdi2290** [comment]
can you pull latest and if you still have a problem you can open another issue thanks
