### ISSUE TITLE
Error loading asyncronously a component with RouteConfig

### ISSUE THREAD

**Issue by sortegam** [AngularClass/angular2-webpack-starter#349]
Hi!

I've been following the guidelines from [here](https://github.com/AngularClass/angular2-webpack-starter/wiki/How-do-I-async-load-a-component-with-AsyncRoute) to get the Async Components loading working with no success.

I've added a new line at @RouteConfig array like this:

```new AsyncRoute({ path: '/builder', loader: () => { require('./builder/builder')('Builder'); } }),```

When I try to enter to /builder route I get this error in the browser:

```
EXCEPTION: TypeError: Cannot read property 'then' of undefined    browser_adapter.js?bab4:85 
```

My builder component syntax is OK and the name of the file is:  builder.async.ts
I don't know what else it could be.
Some help will be appreciated.

PD: The whole stacktrace at the bottom.

Thanks in advance.

S.

```
TypeError: Cannot read property 'then' of undefined
    at AsyncRouteHandler.eval [as _loader] (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:2750:2), <anonymous>:82:24)
    at AsyncRouteHandler.resolveComponentType (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:2720:2), <anonymous>:16:47)
    at RouteRecognizer.recognize (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1210:2), <anonymous>:81:29)
    at eval (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:2732:2), <anonymous>:86:45)
    at Array.forEach (native)
    at Array.forEach (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2093:2), <anonymous>:1107:14)
    at ComponentRecognizer.recognize (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:2732:2), <anonymous>:85:23)
    at RouteRegistry._recognize (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:707:2), <anonymous>:136:33)
    at RouteRegistry.recognize (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:707:2), <anonymous>:119:21)
    at RootRouter.Router.recognize (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:433:2), <anonymous>:356:30)
    at eval (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:433:2), <anonymous>:163:62)
    at Zone.run (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1216:24)
    at Zone.eval [as run] (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:397:2), <anonymous>:344:42)
    at zoneBoundFn (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1193:26)
    at lib$es6$promise$$internal$$tryCatch (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:441:17)
    at lib$es6$promise$$internal$$invokeCallback (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:453:18)
    at eval (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1001:14)
    at eval (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:96:10)
    at microtask (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:397:2), <anonymous>:384:29)
    at Zone.run (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1216:24)
    at Zone.eval [as run] (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:397:2), <anonymous>:344:42)
    at zoneBoundFn (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1193:26)
    at MutationObserver.lib$es6$promise$asap$$flush (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:235:10)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2100:2), <anonymous>:78:29)
    at Zone.eval (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2100:2), <anonymous>:127:47)
    at Zone.bind (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1191:53)
    at bindArguments (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1374:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1386:46)
    at RootRouter.Router.navigateByUrl (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:433:2), <anonymous>:160:66)
    at new RootRouter (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:433:2), <anonymous>:424:14)
    at routerFactory (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:2768:2), <anonymous>:23:22)
    at Injector._instantiate (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:767:27)
    at Injector._instantiateProvider (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:715:25)
    at Injector._new (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:704:21)
    at InjectorDynamicStrategy.getObjByKeyId (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:314:50)
    at Injector._getByKeyDefault (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:902:37)
    at Injector._getByKey (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:848:25)
    at Injector._getByDependency (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:834:25)
    at Injector._instantiate (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:726:36)
    at Injector._instantiateProvider (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:715:25)
    at Injector._new (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:704:21)
    at InjectorInlineStrategy.instantiateProvider (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:204:30)
    at ElementDirectiveInlineStrategy.init (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:237:2), <anonymous>:558:24)
    at new AppElement (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:237:2), <anonymous>:235:28)
    at viewFactory_App0 (viewFactory_App:73:18)
    at HostViewFactory.viewFactory_HostApp0 [as viewFactory] (viewFactory_HostApp:75:1)
    at AppViewManager_.createRootHostView (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:361:2), <anonymous>:94:36)
    at eval (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:231:2), <anonymous>:102:50)
    at Zone.run (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1216:24)
    at Zone.eval [as run] (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:397:2), <anonymous>:344:42)
    at zoneBoundFn (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1193:26)
    at lib$es6$promise$$internal$$tryCatch (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:441:17)
    at lib$es6$promise$$internal$$invokeCallback (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:453:18)
    at lib$es6$promise$$internal$$publish (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:424:12)
    at eval (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:96:10)
    at microtask (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:397:2), <anonymous>:384:29)
    at Zone.run (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1216:24)
    at Zone.eval [as run] (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:397:2), <anonymous>:344:42)
    at zoneBoundFn (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1193:26)
    at MutationObserver.lib$es6$promise$asap$$flush (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:235:10)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2100:2), <anonymous>:78:29)
    at Zone.eval (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2100:2), <anonymous>:127:47)
    at Zone.bind (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1191:53)
    at bindArguments (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1374:36)
    at lib$es6$promise$promise$$Promise.obj.(anonymous function) [as then] (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1386:46)
    at DynamicComponentLoader_.loadAsRoot (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:231:2), <anonymous>:101:51)
    at di_1.provide.useFactory (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:970:2), <anonymous>:29:47)
    at Injector._instantiate (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:764:27)
    at Injector._instantiateProvider (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:715:25)
    at Injector._new (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:704:21)
    at InjectorInlineStrategy.getObjByKeyId (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:217:33)
    at Injector._getByKeyDefault (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:902:37)
    at Injector._getByKey (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:848:25)
    at Injector.get (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:1054:2), <anonymous>:523:21)
    at eval (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:970:2), <anonymous>:328:45)
    at Zone.run (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1216:24)
    at Zone.eval [as run] (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:397:2), <anonymous>:344:42)
    at NgZone.run (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:397:2), <anonymous>:292:40)
    at ApplicationRef_.bootstrap (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:970:2), <anonymous>:319:20)
    at Object.bootstrap (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:2408:2), <anonymous>:101:90)
    at HTMLDocument.main (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:5:2), <anonymous>:25:15)
    at Zone.run (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1216:24)
    at HTMLDocument.zoneBoundFn (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1193:26)

-----async gap-----
Error
    at _getStacktraceWithUncaughtError (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2100:2), <anonymous>:78:29)
    at Zone.eval (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2100:2), <anonymous>:127:47)
    at NgZone._createInnerZone (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:397:2), <anonymous>:332:14)
    at new NgZone (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:397:2), <anonymous>:117:36)
    at createNgZone (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:970:2), <anonymous>:52:12)
    at PlatformRef_.application (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:970:2), <anonymous>:153:33)
    at Object.bootstrap (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:2408:2), <anonymous>:101:64)
    at HTMLDocument.main (eval at <anonymous> (http://localhost:8080/main.bundle-2b3acac2d19e70d2ce00.js:5:2), <anonymous>:25:15)
    at Zone.run (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1216:24)
    at HTMLDocument.zoneBoundFn (eval at <anonymous> (http://localhost:8080/polyfills.bundle-2b3acac2d19e70d2ce00.js:2106:2), <anonymous>:1193:26)

```

**Comment by sortegam** [comment]
Sorry. My bad. 

I wasn't returning a promise in the loader parameter.

I've changed this line:

`new AsyncRoute({ path: '/builder', loader: () => { require('./builder/builder')('Builder'); } }),`

to this:

`new AsyncRoute({ path: '/builder', loader: () => require('./builder/builder')('Builder');  }),`

And now it's working fine.
Sorry for the inconvenience.
S.
