### ISSUE TITLE
Production fail to run at IE11

### ISSUE THREAD

**Issue by ibufu** [AngularClass/angular2-webpack-starter#354]
I have added shims_for_ie.js,and succeed with development at IE 11.
But it failed when js was uglified at IE 11.
There are some information at console:

DEPRECATION WARNING: 'enqueueTask' is no longer supported and will be removed in next major release. Use addTask/addRepeatingTask/addMicroTask
EXCEPTION: SyntaxError: missing';'
STACKTRACE:
SyntaxError: missing';'
   at evalExpression (http://127.0.0.1:8080/main.2e1e8eaffec3e4f2c80a.bundle.js:1:3162)
   at TemplateCompiler.prototype._createViewFactoryRuntime (http://127.0.0.1:8080/main.2e1e8eaffec3e4f2c80a.bundle.js:12:6980)
   at Anonymous function (http://127.0.0.1:8080/main.2e1e8eaffec3e4f2c80a.bundle.js:12:4627)
   at e.prototype.run (http://127.0.0.1:8080/vendor.9ec096512d74b8c635f1.bundle.js:4:21917)
   at Anonymous function (http://127.0.0.1:8080/main.2e1e8eaffec3e4f2c80a.bundle.js:9:2178)
   at Anonymous function (http://127.0.0.1:8080/vendor.9ec096512d74b8c635f1.bundle.js:4:21582)
   at z (http://127.0.0.1:8080/vendor.9ec096512d74b8c635f1.bundle.js:4:16342)
   at A (http://127.0.0.1:8080/vendor.9ec096512d74b8c635f1.bundle.js:4:16430)
   at Anonymous function (http://127.0.0.1:8080/vendor.9ec096512d74b8c635f1.bundle.js:4:19934)
   at Anonymous function (http://127.0.0.1:8080/vendor.9ec096512d74b8c635f1.bundle.js:4:14103)
SyntaxError: missing ';'
DEPRECATION WARNING: 'dequeueTask' is no longer supported and will be removed in next major release. Use removeTask/removeRepeatingTask/removeMicroTask

**Comment by ibufu** [comment]
I am using the latest angular2-webpack-starter,but just change name of polyfills.ts to vendor.ts

**Comment by e-oz** [comment]
see https://github.com/angular/angular/issues/6501

**Comment by ibufu** [comment]
@e-oz 
thx, but I had seen the #6501, and used the shime for IE.then, it succeed to run at IE.But, it failed when js were uglified

**Comment by e-oz** [comment]
@ibufu there is a pull request linked to that task, and it works (tested).

**Comment by ibufu** [comment]
@e-oz Did you uglify JS?

**Comment by wkwiatek** [comment]
The problem is related to mangling. Try to add `mangle: false` to uglify config.

**Comment by e-oz** [comment]
@morning yes

**Comment by e-oz** [comment]
@morning but without mangling

**Comment by gdi2290** [comment]
I updated the repo and included `ie-shim` there may also be problems with the Angular 2 repo and there is currently production issues with uglify. You can open another issue if you still have the problem
