### ISSUE TITLE
Error: Cannot find module 'tapable'

### ISSUE THREAD

**Issue by lewis617** [AngularClass/angular2-webpack-starter#423]
* **I'm submitting a ...**
[ ] bug report
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'tapable'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\code\angular2-webpack-starter\node_modules\webpack\lib\Compiler.js:6:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server:dev" "--" "--hot"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@3.0.0 server:dev: `webpack-dev-server --inline --progress --profile --colors --watch --display-error-details --display-cached --content-base src/ "--hot"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@3.0.0 server:dev script 'webpack-dev-server --inline --progress --profile --colors --watch --display-error-details --display-cached --content-base src/ "--hot"'.
npm ERR! This is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --progress --profile --colors --watch --display-error-details --display-cached --content-base src/ "--hot"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular2-webpack-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\code\angular2-webpack-starter\npm-debug.log
```

I just run`npm install typings webpack-dev-server -g` `npm install ` and `npm start`,according to readme.md quick start

* **my environment:**

- Windows 7

**Comment by gdi2290** [comment]
are you on the latest version of npm and node?

**Comment by lewis617** [comment]
@gdi2290 
node version is 4.4

**Comment by gdi2290** [comment]
@lewis617 can you delete `node_modules/` and run `npm install` again?

**Comment by lewis617** [comment]
@gdi2290  I try many times ,  maybe I should use ubuntu or mac

**Comment by ismailmdau** [comment]
The following worked for me
https://stackoverflow.com/questions/45843293/ng-serve-cannot-find-module-tapable
