### ISSUE TITLE
Error when running npm run server

### ISSUE THREAD

**Issue by ericmasiello** [AngularClass/angular2-webpack-starter#427]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

After running `npm install`, I attempted to run `npm run server`.  However, when I try to run it I get the following error:

```
ERROR in ./src/app/bootstrap.ts
Module build failed: TypeError: undefined is not a function
    at readConfig (/Users/masielle/Sites/angular2-webpack-starter/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:51:15)
    at createInstance (/Users/masielle/Sites/angular2-webpack-starter/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:62:18)
    at getLoaderInstance (/Users/masielle/Sites/angular2-webpack-starter/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:163:20)
    at Object.loader (/Users/masielle/Sites/angular2-webpack-starter/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:12:14)
 @ multi app
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by mmgyce** [comment]
Instead of npm run server, type **npm start** or **npm run start**
