### ISSUE TITLE
Can't add one more route in @RouteConfig

### ISSUE THREAD

**Issue by Skholastik** [AngularClass/angular2-webpack-starter#438]
Hello everybody! I'm faced with one simple problem: i just can't build my proj if i'm adding in @RouteConfig one more route, for example: 
`@RouteConfig([
  { path: '/',      name: 'Index', component: Home, useAsDefault: true },
  { path: '/home',  name: 'Home',  component: Home },
  { path: '/adminRoot',  name: 'AdminRoot',  component: AdminRoot },
`
**That error log:**

`D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp>npm run build:prod

> angular2-webpack-starter@3.0.0 prebuild:prod D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp
> npm run clean:dist

> angular2-webpack-starter@3.0.0 clean:dist D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp
> rimraf dist

> angular2-webpack-starter@3.0.0 build:prod D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp
> webpack --config webpack.prod.config.js --progress --profile --colors --display-error-details --display-cached --bail

 39% 63/130 build modulesModuleBuildError: Module build failed: Error: Compilation failed due to tslint errors.

D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\src\app\app.component.ts
[55, 1]: exceeds maximum line length of 100

    at report (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\tslint-loader\index.js:82:11)
    at Object.lint (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\tslint-loader\index.js:66:3)
    at Object.module.exports (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\tslint-loader\index.js:151:8)
    at DependenciesBlock.onModuleBuildFailed (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:31
5:19)
    at nextLoader (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:270:31)
    at D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:292:15
    at runSyncOrAsync (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:173:4)
    at nextLoader (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:290:3)
    at D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.provide (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:1
40:24)
    at DependenciesBlock.onLoadPitchDone (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:255:7)

    at DependenciesBlock.loadPitch (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:182:27)
    at DependenciesBlock.loadPitch (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:186:21)
    at DependenciesBlock.loadPitch (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:223:61)
    at DependenciesBlock.loadPitch (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:186:21)
    at DependenciesBlock.loadPitch (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:223:61)
    at DependenciesBlock.doBuild (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack-core\lib\NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\lib\NormalModule.js:84:14)
    at Compilation.buildModule (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\lib\Compilation.js:126:9)
    at D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\lib\Compilation.js:309:10
    at D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\tapable\lib\Tapable.js:75:69)
    at onDoneResolving (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:38:11)
    at onDoneResolving (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:121:6)
    at D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:116:7
    at D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\node_modules\async\lib\async.js:726:13
    at D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at async.forEachOf.async.eachOf (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\node_modules\async\lib\async.js:236:30)
    at _parallel (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\node_modules\async\lib\async.js:717:9)
    at Object.async.parallel (D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\node_modules\async\lib\async.js:731:9)
    at D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:109:12
    at D:\Proj\AllProjects\TestBlackUnicorn\src\main\webapp\node_modules\webpack\node_modules\async\lib\async.js:726:13

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Tools\\NodeJs\\node.exe" "C:\\Tools\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:prod"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@3.0.0 build:prod: `webpack --config webpack.prod.config.js --progress --profile --colors --display-error-details --dis
play-cached --bail`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@3.0.0 build:prod script 'webpack --config webpack.prod.config.js --progress --profile --colors --display
-error-details --display-cached --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack-starter package,
npm ERR! not with npm itself.
`
From despair i'm just try to change names of class,directory, those i didn't change logic or smth else and nothing heps.

**Comment by abdulhaq-e** [comment]
> Error: Compilation failed due to tslint errors.

When running in production mode, any tslint erros will stop the build process. Try to do a dev build and see that it is working fine.

**Comment by Skholastik** [comment]
Thank you very-very-very much,abdulhaq-e ! I'm battle with this prob all day....in "dev" mode it works fine, but in "prod" mode it could work fine too, we just need to change : ** failOnHint: true** to  ** failOnHint: false**

**Comment by gdi2290** [comment]
you can remove tslint from the production config
