### ISSUE TITLE
browser_adapter.ts:73 EXCEPTION: Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by arozwalak** [AngularClass/angular2-webpack-starter#465]
I just cloned latest version of angular2-webpack-starter and setup my project. When I run `npm run server` it works ok, but when I try to get prod version with `npm run build:prod` and `npm run server:prod` I'm getting this error:

```
browser_adapter.ts:73 EXCEPTION: Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
```

this is stack trace: 

```
t.logError	@	browser_adapter.ts:73
e.call	@	exception_handler.ts:52
(anonymous function)	@	application_ref.ts:258
t.object.i	@	async.ts:127
t.__tryOrUnsub	@	Subscriber.js:166
t.next	@	Subscriber.js:115
t._next	@	Subscriber.js:74
t.next	@	Subscriber.js:51
t._finalNext	@	Subject.js:124
t._next	@	Subject.js:116
t.next	@	Subject.js:73
t.emit	@	async.ts:113
_zoneImpl.i.NgZoneImpl.onError	@	ng_zone.ts:134
inner.inner.fork.onHandleError	@	ng_zone_impl.ts:88
t.handleError	@	zone.ts:703
t.runGuarded	@	zone.ts:557
i	@	zone.ts:886
invoke	@	zone.ts:811
```

```
zone.ts:855 Unhandled Promise rejection: Maximum call stack size exceeded ; Zone: angular ; Task: Promise.then ; Value: RangeError: Maximum call stack size exceeded
    at e._instantiate (http://localhost:8080/vendor.82d45b5a31d9cd9d56a5.bundle.js:15:3619)
    at e._instantiateProvider (http://localhost:8080/vendor.82d45b5a31d9cd9d56a5.bundle.js:15:1456)
    at e._new (http://localhost:8080/vendor.82d45b5a31d9cd9d56a5.bundle.js:15:1185)
    at e.instantiateProvider (http://localhost:8080/vendor.82d45b5a31d9cd9d56a5.bundle.js:14:28611)
    at e.init (http://localhost:8080/vendor.82d45b5a31d9cd9d56a5.bundle.js:5:19934)
    at new e (http://localhost:8080/vendor.82d45b5a31d9cd9d56a5.bundle.js:5:12832)
    at viewFactory_t0 (viewFactory_t:82:16)
    at viewFactory_t0 (viewFactory_t:84:1)
    at viewFactory_t0 (viewFactory_t:84:1)
    at viewFactory_t0 (viewFactory_t:84:1)
```

**Comment by antonmoiseev** [comment]
Try disabling mangling [here](https://github.com/AngularClass/angular2-webpack-starter/blob/7bcfbd90b7cc55ac86634166a6fa8ebd46a047af/config/webpack.prod.js#L292): `mangle: false`.

**Comment by elvirdolic** [comment]
is this something related to the current angular beta 12 version? 
I have the same issue and it only works when disabling mangle.

**Comment by gdi2290** [comment]
I turned mangle to false so this problem won't happen again
