### ISSUE TITLE
Failed to exec build:prod script

### ISSUE THREAD

**Issue by thunderrun** [AngularClass/angular2-webpack-starter#510]
* **I'm submitting a ...**
bug report

* **What is the current behavior?**
when i run `npm run build:prod` on a fresh clone, i got the following error `TypeError: Cannot read property 'substr' of undefined` 

```bash
 80% optimize chunk assets
/Users/norman/angular2-webpack-starter/node_modules/.npminstall/source-map/0.4.4/source-map/lib/source-map/source-node.js:100
            var code = nextLine.substr(0, mapping.generatedColumn -
                               ^
TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/source-map/0.4.4/source-map/lib/source-map/source-node.js:100:32)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/source-map/0.4.4/source-map/lib/source-map/source-map-consumer.js:159:16)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/source-map/0.4.4/source-map/lib/source-map/source-node.js:84:26)
    at SourceMapSource.node (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/SourceMapSource.js:41:20)
    at ReplaceSource.node (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/ReplaceSource.js:64:29)
    at CachedSource.node (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/CachedSource.js:41:22)
    at PrefixSource.node (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/PrefixSource.js:27:26)
    at /Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/ConcatSource.js:38:49
    at Array.map (native)
    at ConcatSource.node (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/ConcatSource.js:37:60)
    at /Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/ConcatSource.js:38:49
    at Array.map (native)
    at ConcatSource.node (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/ConcatSource.js:37:60)
    at /Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/ConcatSource.js:38:49
    at Array.map (native)
    at ConcatSource.node (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/ConcatSource.js:37:60)
    at /Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/ConcatSource.js:38:49
    at Array.map (native)
    at ConcatSource.node (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/ConcatSource.js:37:60)
    at ConcatSource.proto.sourceAndMap (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/SourceAndMapMixin.js:22:18)
    at CachedSource.sourceAndMap (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack-core/0.6.8/webpack-core/lib/CachedSource.js:34:28)
    at Compilation.<anonymous> (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack/1.13.0/webpack/lib/SourceMapDevToolPlugin.js:55:32)
    at Array.map (native)
    at Compilation.<anonymous> (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack/1.13.0/webpack/lib/SourceMapDevToolPlugin.js:43:84)
    at Array.forEach (native)
    at Compilation.<anonymous> (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack/1.13.0/webpack/lib/SourceMapDevToolPlugin.js:42:11)
    at Compilation.applyPlugins (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/tapable/0.1.10/tapable/lib/Tapable.js:26:37)
    at Compilation.<anonymous> (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/webpack/1.13.0/webpack/lib/Compilation.js:571:10)
    at Compilation.next (/Users/norman/angular2-webpack-starter/node_modules/.npminstall/tapable/0.1.10/tapable/lib/Tapable.js:67:11)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Follow the Quick start guide and works well calling `npm start`, but run into error when calling `npm run build:prod`

* **Please tell us about your environment:**
OS X 10.11.4
node v5.10.1
npm v3.8.3

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Here's the npm-debug.log file
```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:prod' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle angular2-webpack-starter@5.0.4~prebuild:prod: angular2-webpack-starter@5.0.4
6 verbose lifecycle angular2-webpack-starter@5.0.4~prebuild:prod: unsafe-perm in lifecycle true
7 verbose lifecycle angular2-webpack-starter@5.0.4~prebuild:prod: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/norman/Sites/angular2-webpack-starter/node_modules/.bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle angular2-webpack-starter@5.0.4~prebuild:prod: CWD: /Users/norman/Sites/angular2-webpack-starter
9 silly lifecycle angular2-webpack-starter@5.0.4~prebuild:prod: Args: [ '-c', 'npm run clean:dist' ]
10 silly lifecycle angular2-webpack-starter@5.0.4~prebuild:prod: Returned: code: 0  signal: null
11 info lifecycle angular2-webpack-starter@5.0.4~build:prod: angular2-webpack-starter@5.0.4
12 verbose lifecycle angular2-webpack-starter@5.0.4~build:prod: unsafe-perm in lifecycle true
13 verbose lifecycle angular2-webpack-starter@5.0.4~build:prod: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/norman/Sites/angular2-webpack-starter/node_modules/.bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
14 verbose lifecycle angular2-webpack-starter@5.0.4~build:prod: CWD: /Users/norman/Sites/angular2-webpack-starter
15 silly lifecycle angular2-webpack-starter@5.0.4~build:prod: Args: [ '-c',
15 silly lifecycle   'webpack --config config/webpack.prod.js  --progress --profile --colors --display-error-details --display-cached --bail' ]
16 silly lifecycle angular2-webpack-starter@5.0.4~build:prod: Returned: code: 1  signal: null
17 info lifecycle angular2-webpack-starter@5.0.4~build:prod: Failed to exec build:prod script
18 verbose stack Error: angular2-webpack-starter@5.0.4 build:prod: `webpack --config config/webpack.prod.js  --progress --profile --colors --display-error-details --display-cached --bail`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at EventEmitter.emit (events.js:185:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at ChildProcess.emit (events.js:185:7)
18 verbose stack     at maybeClose (internal/child_process.js:850:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
19 verbose pkgid angular2-webpack-starter@5.0.4
20 verbose cwd /Users/norman/Sites/angular2-webpack-starter
21 error Darwin 15.4.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:prod"
23 error node v5.10.1
24 error npm  v3.8.3
25 error code ELIFECYCLE
26 error angular2-webpack-starter@5.0.4 build:prod: `webpack --config config/webpack.prod.js  --progress --profile --colors --display-error-details --display-cached --bail`
26 error Exit status 1
27 error Failed at the angular2-webpack-starter@5.0.4 build:prod script 'webpack --config config/webpack.prod.js  --progress --profile --colors --display-error-details --display-cached --bail'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular2-webpack-starter package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     webpack --config config/webpack.prod.js  --progress --profile --colors --display-error-details --display-cached --bail
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular2-webpack-starter
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular2-webpack-starter
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

**Comment by thunderrun** [comment]
I found the problem: 
node_modules is not correctly installed because of network problem in China even if you changed registry source.
You have to download come other content form AWS while running `npm install`.
And do not try use `cnpm` because some of its commands are conflict with npm.

**Comment by gdi2290** [comment]
@thunderrun can you include cnpm in the wiki?
https://github.com/AngularClass/angular2-webpack-starter/wiki

**Comment by thunderrun** [comment]
`cnpm` fixed the bug and it's now able to install correctly.
