### ISSUE TITLE
npm run server - getting errors

### ISSUE THREAD

**Issue by alvipeo** [AngularClass/angular2-webpack-starter#517]
My project is based on this great repo, so I try to follow it. But I don't use ng2 material so it's slightly different. I just upgraded to the current version of the repo and I get error when 'npm run server':

>d:\source\index.js:30
        throw new Error('CopyWebpackPlugin: to use webpack-dev-server, devServer.outputPath must be defined in the webpack config');
              ^
Error: CopyWebpackPlugin: to use webpack-dev-server, devServer.outputPath must be defined in the webpack config
    at getOutputDir (d:\source\index.js:30:15)
    at Object.apply (d:\source\index.js:43:28)
    at Compiler.apply (d:\Documents\Visual Studio 2015\Projects\UniGalleryCode\node_modules\tapable\lib\Tapable.js:164:16)
    at OptionsApply.WebpackOptionsApply.process (d:\Documents\Visual Studio 2015\Projects\UniGalleryCode\node_modules\webpack\lib\WebpackOptionsApply.js:62:18)
    at webpack (d:\Documents\Visual Studio 2015\Projects\UniGalleryCode\node_modules\webpack\lib\webpack.js:22:48)
    at Object.<anonymous> (d:\Documents\Visual Studio 2015\Projects\UniGalleryCode\node_modules\webpack-dev-server\bin\webpack-dev-server.js:158:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

>npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server:dev"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack-starter@5.0.4 server:dev: `webpack-dev-server --config config/webpack.dev.js --inline --progress --profile --colors --watch --display-error-details --display-cached --content-base src/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack-starter@5.0.4 server:dev script 'webpack-dev-server --config config/webpack.dev.js --inline --progress --profile --colors --watch --display-error-details --display-cached --content-base src/'.

But 'npm run build' works. I tried this and that and can't fix it. Could anyone help please?

**Comment by AlexFrazer** [comment]
Same problem here

**Comment by t0rrro** [comment]
Set outputPath in the devServer plugin. If you using the same setup, add the outputPath property to devServer in webpack.dev.js. If you are building to dist make it '../dist'

**Comment by alvipeo** [comment]
Thanks! That one worked!
