### ISSUE TITLE
Issue webpack.common

### ISSUE THREAD

**Issue by alapasset** [AngularClass/angular2-webpack-starter#584]
Hello,

Since i have update angular-webpack this week i can't build my solution. I have that : 

> TypeError: CopyWebpackPlugin is not a constructor
    at Object.<anonymous> (...\config\webpack.common.js:231:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...\config\webpack.dev.js:7:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at module.exports (...\node_modules\webpack-dev-server\bin\webpack-dev-server.js:55:48)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)

Thx.

**Comment by jmbarbier** [comment]
`npm install copy-webpack-plugin@2.1.3` temporary does the trick, see #585

**Comment by alapasset** [comment]
Thx :) 

But a i have another issue but whith build:prod :

` at ...\node_modules\webpack\lib\Compilation.js:254:7
    at ...\node_modules\webpack\lib\NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (...\node_modules\tapable\lib\Tapable.js:75:69)
    at onDoneResolving (...\node_modules\webpack\lib\NormalModuleFactory.js:38:11)
    at onDoneResolving (...\node_modules\webpack\lib\NormalModuleFactory.js:121:6)
    at ...\node_modules\webpack\lib\NormalModuleFactory.js:116:7
    at ...\node_modules\webpack\node_modules\async\lib\async.js:726:13
    at ...\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (...\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at ...\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at ...\node_modules\webpack\node_modules\async\lib\async.js:723:17
    at ...\node_modules\webpack\node_modules\async\lib\async.js:167:37
    at ...\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at ...\node_modules\webpack\node_modules\async\lib\async.js:361:13
    at ...\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (...\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at ...\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at ...\node_modules\webpack\node_modules\async\lib\async.js:358:17
    at ...\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:29:4
    at onResolved (...\node_modules\enhanced-resolve\lib\Resolver.js:39:10)
    at innerCallback (...\node_modules\enhanced-resolve\lib\Resolver.js:89:22)
    at loggingCallbackWrapper (...\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19)
    at ...\node_modules\tapable\lib\Tapable.js:134:6
    at ...\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:55:11
    at ...\node_modules\enhanced-resolve\lib\Resolver.js:191:15
    at Tapable.<anonymous> (...\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:50:12)
    at Storage.finished (...\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at FSReqWrap.oncomplete (fs.js:117:15)`

**Comment by alapasset** [comment]
someone have an idee ?
