### ISSUE TITLE
copy-webpack-plugin 2.1.4 fails

### ISSUE THREAD

**Issue by jmbarbier** [AngularClass/angular2-webpack-starter#585]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**

Failing to start webpack - copy-webpack-plugin issue : https://github.com/kevlened/copy-webpack-plugin/issues/46

forcing 2.1.3 makes it ok

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

- clone angular2-webpack-starter
- npm install
- npm start

```
jmbarbier@iznogoud ~/D/s/angular2-webpack-starter> npm start

> angular2-webpack-starter@5.0.4 start /Users/jmbarbier/Devel/sandbox/angular2-webpack-starter
> npm run server:dev


> angular2-webpack-starter@5.0.4 server:dev /Users/jmbarbier/Devel/sandbox/angular2-webpack-starter
> webpack-dev-server --config config/webpack.dev.js --inline --progress --profile --colors --watch --display-error-details --display-cached --content-base src/

root directory: /Users/jmbarbier/Devel/sandbox/angular2-webpack-starter
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node) crypto.Credentials is deprecated. Use tls.createSecureContext instead.

/Users/jmbarbier/Devel/sandbox/angular2-webpack-starter/config/webpack.common.js:232
    new CopyWebpackPlugin([{
    ^
TypeError: CopyWebpackPlugin is not a function
    at Object.<anonymous> (/Users/jmbarbier/Devel/sandbox/angular2-webpack-starter/config/webpack.common.js:232:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/jmbarbier/Devel/sandbox/angular2-webpack-starter/config/webpack.dev.js:7:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at module.exports (/Users/jmbarbier/Devel/sandbox/angular2-webpack-starter/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/jmbarbier/Devel/sandbox/angular2-webpack-starter/node_modules/webpack-dev-server/bin/webpack-dev-server.js:55:48)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
```

**Comment by CristyTarantino** [comment]
+1

**Comment by ditoglez** [comment]
+1
As a temporary hack solution:

`var CopyWebpackPlugin = require('copy-webpack-plugin').default;`

**Comment by vesteraas** [comment]
...or setting version to "2.1.3"

**Comment by chief10** [comment]
+1

Except mine is like this:
```
const CopyWebpackPlugin = (CopyWebpackPlugin = require('copy-webpack-plugin'), CopyWebpackPlugin.default || CopyWebpackPlugin);
                                                                                                ^

TypeError: Cannot read property 'default' of undefined
```

**Comment by jmbarbier** [comment]
2.1.5 and 2.1.6 are pushed fixing this bug

**Comment by MangeshPimpalkar** [comment]
@jmbarbier Is this still happening.
I am still getting this error.

**Comment by phiphou** [comment]
@jmbarbier No, it should work, the project now use `copy-webpack-plugin@3.0.1`, witch is the latest stable version.

Maybe you should try to delete and re-install this module : 

`$ npm remove copy-webpack-plugin -D`
`$ npm i copy-webpack-plugin -D`

**Comment by gdi2290** [comment]
ya it should work
npm remove copy-webpack-plugin -D
npm cache clean
npm i copy-webpack-plugin -D
