### ISSUE TITLE
Build Prod

### ISSUE THREAD

**Issue by alapasset** [AngularClass/angular2-webpack-starter#598]
Hello everyone,

i have an issue but whith build:prod :

`ModuleNotFoundError: Module not found: Error: a dependency to an entry point is not allowed
at ...\node_modules\webpack\lib\Compilation.js:254:7 at ...\node_modules\webpack\lib\NormalModuleFactory.js:58:13 at NormalModuleFactory.applyPluginsAsyncWaterfall (...\node_modules\tapable\lib\Tapable.js:75:69) at onDoneResolving (...\node_modules\webpack\lib\NormalModuleFactory.js:38:11) at onDoneResolving (...\node_modules\webpack\lib\NormalModuleFactory.js:121:6) at ...\node_modules\webpack\lib\NormalModuleFactory.js:116:7 at ...\node_modules\webpack\node_modules\async\lib\async.js:726:13 at ...\node_modules\webpack\node_modules\async\lib\async.js:52:16 at done (...\node_modules\webpack\node_modules\async\lib\async.js:246:17) at ...\node_modules\webpack\node_modules\async\lib\async.js:44:16 at ...\node_modules\webpack\node_modules\async\lib\async.js:723:17 at ...\node_modules\webpack\node_modules\async\lib\async.js:167:37 at ...\node_modules\webpack\node_modules\async\lib\async.js:52:16 at ...\node_modules\webpack\node_modules\async\lib\async.js:361:13 at ...\node_modules\webpack\node_modules\async\lib\async.js:52:16 at done (...\node_modules\webpack\node_modules\async\lib\async.js:246:17) at ...\node_modules\webpack\node_modules\async\lib\async.js:44:16 at ...\node_modules\webpack\node_modules\async\lib\async.js:358:17 at ...\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:29:4 at onResolved (...\node_modules\enhanced-resolve\lib\Resolver.js:39:10) at innerCallback (...\node_modules\enhanced-resolve\lib\Resolver.js:89:22) at loggingCallbackWrapper (...\node_modules\enhanced-resolve\lib\createInnerCallback.js:21:19) at ...\node_modules\tapable\lib\Tapable.js:134:6 at ...\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:55:11 at ...\node_modules\enhanced-resolve\lib\Resolver.js:191:15 at Tapable.<anonymous> (...\node_modules\enhanced-resolve\lib\ModulesInDirectoriesPlugin.js:50:12) at Storage.finished (...\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16) at FSReqWrap.oncomplete (fs.js:117:15)`

Any idea ?

Thx!

**Comment by IAMtheIAM** [comment]
Which version of Node? I recommend 4.4.4 LTS

**Comment by valdemarrolfsen** [comment]
I have the same problem when running the 'npm run build:prod' command. 

The part that fails is:

webpack --config config/webpack.prod.js  --progress --profile --colors --display-error-details --display-cached --bail

Node version:
4.4.5

Npm version:
2.15.5

Stack trace:

build modulesModuleNotFoundError: Module not found: Error: a dependency to an entry point is not allowed
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/lib/Compilation.js:254:7
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/lib/NormalModuleFactory.js:116:7
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:361:13
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/webpack/node_modules/async/lib/async.js:358:17
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:29:4
    at onResolved (/Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/enhanced-resolve/lib/Resolver.js:39:10)
    at innerCallback (/Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/enhanced-resolve/lib/Resolver.js:89:22)
    at loggingCallbackWrapper (/Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/tapable/lib/Tapable.js:134:6
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:55:11
    at /Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at Tapable.<anonymous> (/Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:50:12)
    at Storage.finished (/Users/valdemarrolfsen/Utvikling/Applikasjoner/moj-web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by valdemarrolfsen** [comment]
Sorry, the wrong version of node was not completely removed. Got it working!
