### ISSUE TITLE
How to use a React component in a .tsx file

### ISSUE THREAD

**Issue by Renaud009** [AngularClass/angular2-webpack-starter#671]
Hello,

I fail to use a react component in the current angular2-webpack-starter who uses angular2.0.0-rc.1
I followed some guidelines mainly
https://github.com/LookLikeAPro/Angular-2-React-Example and https://www.npmjs.com/package/react-dom

My current error is a fail at compile:
<pre><code>ERROR in ./src/app/schema-form/react-wrapper.js
Module parse failed: /home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/source-map-loader/index.js!/home/osboxes/workspace/psc-portal/adnotare-psc/src/app/schema-form/react-wrapper.js Unexpected token (15:15)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (15:15)
    at Parser.pp.raise (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.unexpected (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:1483:8)
    at Parser.pp.parseExprAtom (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:330:12)
    at Parser.pp.parseExprSubscripts (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:225:19)
    at Parser.pp.parseMaybeUnary (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:204:17)
    at Parser.pp.parseExprOps (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:110:19)
    at Parser.pp.parseExpression (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:86:19)
    at Parser.pp.parseReturnStatement (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:1854:26)
    at Parser.pp.parseStatement (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:1719:19)
    at Parser.pp.parseBlock (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:1991:21)
    at Parser.pp.parseFunctionBody (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:607:22)
    at Parser.pp.parseFunction (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:2071:8)
    at Parser.pp.parseExprAtom (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:318:19)
    at Parser.pp.parseExprSubscripts (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:225:19)
    at Parser.pp.parseMaybeUnary (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:204:17)
    at Parser.pp.parseExprOps (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:151:19)
    at Parser.pp.parseMaybeConditional (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:110:19)
    at Parser.pp.parseMaybeAssign (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:120:23)
    at Parser.pp.parseExpression (/home/osboxes/workspace/psc-portal/adnotare-psc/node_modules/acorn/dist/acorn.js:86:19)
 @ ./src/app/schema-form/schema-form.component.ts 4:22-48
</pre></code>

**What I have done so far:**

installed packages and typings
<pre><code>npm install react react-dom --save
typings install dt~react --global --save
typings install dt~react-dom --global --save
</pre></code>

modified tsconfig.json (added jsx support)
<pre><code>"compilerOptions": {
    "jsx": "react",
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noEmitHelpers": true
  }
</pre></code>

modified config/webpack.common.js
<pre><code>resolve: {
...
    extensions: ['', '.ts', '.js', '.tsx'],
...
}
loaders: [
...
loader`
      {
        test: /\.tsx?$/,
        loader: 'awesome-typescript-loader',
        exclude: [/\.(spec|e2e)\.tsx?$/]
      },
...
]
</pre></code>

used and modified the content of npm package angular2-react and inserted the folder inside my component folder for prototyping purpose, here's the content of my schema-form folder:

- angular2-react
- - component.ts
- - react.ts
- - react-dom.ts
- react-wrapper.tsx
- schema-form.component.ts

Here's the current content of every file:

angular2-react/component.ts
<pre><code>import React from "./react";
import ReactDOM from "./react-dom";
import {Component} from '@angular/core';

@Component({
    selector: 'react-component',
    template: '\<div [id]="id"\>wrapper\</div\>',
    inputs: ['component', 'props']
})
export class ReactComponent {
    component: any;
    props: Object;
    id: number;
    drawNode: any;
    ngOnInit() {
        this.id = Math.floor(Math.random() * 9999999);
    }
    ngAfterViewInit() {
        this.drawNode = document.getElementById(this.id.toString());
		this.render();
    }
    ngOnChanges() {
        if (this.drawNode) {
			this.render();
        }
    }
    render() {
		  ReactDOM.render(React.createElement(this.component, this.props), this.drawNode);
    }
}
</pre></code>

react.ts
<pre><code>/// \<reference path="../../../../typings/globals/react/index.d.ts" /\>
import * as React from "react";
export default React;
</pre></code>

react-dom.ts
<pre><code>/// \<reference path="../../../../typings/globals/react-dom/index.d.ts" /\>
import * as ReactDOM from "react-dom";
export default ReactDOM;
</pre></code>

react-wrapper.tsx
<pre><code>import React from "./angular2-react/react";
interface MyComponentProps {
  name: string;
}
export default class ReactWrapper extends React.Component<MyComponentProps, any> {
  render() {
    const {name} = this.props;
    return \<div\>Hi {name}, this is a react component and my props is {JSON.stringify(this.props)}|\</div\>;
  }
}
</pre></code>

schema-form.component.ts
<pre><code>
import { Component } from '@angular/core';
import {ReactComponent} from './angular2-react/component';
import ReactWrapper from './react-wrapper';
@Component({
  selector: 'schema-form',
  styles: [`
  `],
  directives: [ReactComponent],
  template: `<h1>My First Angular App</h1><react-component [component]="embedComponent" [props]="embedComponentProps"></react-component>`
})
export class SchemaForm {
  embedComponent = ReactWrapper;
  embedComponentProps = {
    "name": "person"
  };
}
</pre></code>

I am thinking this has to do with awesome-typescript-loader that can't handle tsx file type, but I have no idea what to change at this point. Any ideas or tips would be appreciated.

Thank you

**Comment by Renaud009** [comment]
Actually adding lines or anything more generic in tsconfig.json helped
<pre><code>"files": [
    "./src/app/schema-form/react-wrapper.tsx"
  ],</code></pre>
